// Shared prompt building blocks for LinkedIn post generation.
//
// These constants used to live inline in backend/src/routes/ideas.ts and were
// only injected when the user generated ideas through Inspiration → Generate.
// The Post Creator chat (backend/src/routes/chat.ts) had its own briefer
// system prompt and missed everything below — including the VIDEO_SCRIPT
// block (the user expected `mention "video"` to work in Post Creator too).
//
// Extracted here as the single source of truth so the next prompt revision
// updates both surfaces in one place. Last drift to fix: rules #8 / #10 /
// #11 / #12 / #13 had to be applied twice in the previous weeks.
//
// All exports are pure string constants (or a pure helper). No DB, no
// network, no per-request state — they're constant prompt fragments.

// Hard rules baked into every post generated by the Post Creator. These
// reflect commercial reality, not stylistic preferences:
// - LinkedIn distribution favours reposts above any other engagement metric;
//   a company that gets criticised in your post will never repost it, so the
//   downside vs. the upside is heavily asymmetric. Frame any mention positive.
// - Neety's audience is broadly medium/large B2B companies. Industrial
//   exporters are a strong recurring segment (proven in the 15.9x regional-
//   map outliers) but NOT exclusive — many clients are B2B services, SaaS,
//   etc. Don't force every post into an industrial frame.
export const BRAND_RULES = `BRAND & AUDIENCE RULES (non-negotiable):
- NEVER criticise, mock, or speak negatively about any other company, brand, tool or competitor by name. Any mention of another product, software, or company MUST be positive or neutral-respectful — never negative. Reposts are LinkedIn's highest-leverage metric and a criticised company won't repost; the upside of a sharp jab almost never beats the lost reach.
- If you need a counter-example, talk about a generic pattern ("most CRMs", "the average outbound playbook") rather than naming a specific company.
- ATTACK THE PROBLEM, NEVER THE READER. Outliers in our data confront a situation, a system, or a market — they do NOT point at the reader ("tú haces X mal", "you're doing this wrong", "you don't understand"). Direct second-person criticism triggers defensive rejection and kills engagement. Frame the wound as something happening TO people in the reader's role ("most SDRs are losing X to Y", "the typical outbound process is broken in this way"), not as a personal failing the reader is committing. The reader should nod at the diagnosis, never feel attacked.
- Neety's audience is BROADLY medium/large B2B companies. Industrial exporters are a strong recurring segment (and a proven angle in winning posts — e.g. the 15.9x regional-map outliers) but NOT exclusive: B2B service companies, SaaS, agencies' B2B clients, consultancies, and other B2B segments all fit too. DO NOT assume every post must be industrial-flavoured. When you have latitude on examples or framing, pick the segment that best fits the raw idea — if the idea is industrial, lean industrial; if it's a SaaS / B2B-services angle, lean that way. Forcing every post into the industrial frame is a known failure mode.`;

// Pulled from 2 weeks of real publishing data on this account. These complement
// the global outlier pool — they tell the model which patterns produced reposts
// and saves for THIS specific account vs which fell flat. Treat as a heavy
// prior on top of the archetype.
export const CREATOR_LEARNINGS = `CREATOR LEARNINGS (from 2 weeks of real publishing on this account — apply on top of the archetype):

LEAN HARD INTO (top performers, e.g. 20x outliers):
- "Insight + hidden system + contrarian": show how something actually works behind the scenes — a mechanic, an incentive, a distribution rule, a pattern that most people in the audience don't see. Pair with concrete data when possible.
- Break the reader's default belief inside the first 1–3 lines. The hook should make them think "wait, that's not how I thought it worked".
- Mix data WITH narrative. A specific number anchored in a story beats either pure data or pure story.

ACCEPTABLE BUT WEAKER (use only when the raw idea genuinely fits):
- Pure provocation + universal-problem framing (e.g. "lead-magnet prospecting messages"). Drives comments but lower repost rate.

NEVER PRODUCE:
- Generic posts that ANY creator in the niche could publish. If swapping the author name wouldn't change the content's credibility, the post is too generic — rewrite it with a hidden-system angle or a specific anecdote.
- AI-news recaps without the author's own framing or hidden insight on top.
- Opinions with no proof: claims that aren't backed by a number, a specific anecdote, or a named case.
- "Personal" posts without an edge (birthday/gratitude/milestone with no sharp lesson). If the post is personal, it must contain a concrete takeaway the reader can use.

THE WIN/LOSE TEST: a post WINS when it (a) explains how a system actually works AND (b) breaks a commonly held belief. A post LOSES when it reads like it could've been ghostwritten for any creator in the niche.`;

// Distilled from a research pass over ~45 top-performing B2B AI / sales
// founders on LinkedIn (EN + ES). These are the structural moves that
// separated 60-1.000+ like posts from generic noise. Treat as a heavy prior
// the model can apply whenever the raw idea has latitude — without forcing
// the framing if the idea genuinely doesn't fit.
export const POSITIONING_PRINCIPLES = `POSITIONING PRINCIPLES (research-backed — apply whenever the raw idea has latitude):

THE 5 LEVERS:
1. Position by CONTRAST, not features. "Most teams do X. We do Y because Z" outperforms "We do Y very well". Lead by naming what's broken in the default playbook before saying what we do.
2. Client numbers beat self-praise. "+200 PYMES, +40% conversion" lands harder than "best AI sales platform". When a real client metric exists, use it.
3. Lead with a market frame, not a product feature. Recurring contrasts like "operativa vs. operacional", "agentic vs. tool", "signal vs. cold volume", "ejecución vs. gestión" carry the post; bare feature descriptions read as ad copy.
4. Reuse one concept word that's ours. A single term repeated across posts builds a category in the reader's head.
5. Founder name > product name. The post sells the thinker; mention the product at most once near the end, not in the hook.

5 HIGH-CONVICTION POST PATTERNS — pick one when the raw idea genuinely fits:
- Anti-consensus on a hot category. "Everyone's launching AI SDRs. Most are flopping. Here's what actually moves outbound."
- Founder microstory with a specific moment. "Closed a customer at 18:02 on a Saturday. No human would have. The agent did."
- Numbered workflow with concrete tool stack. "Agent 1 captures X. Agent 2 enriches Y. Agent 3 decides Z." Each step has a real output.
- Market thesis with hard numbers (CAC, reply rate, ARR comps) the reader can't easily argue with.
- "Deciding in public" — "Considering X vs Y for [decision]. Trade-off as I see it: [...]. What would you do?"

AUTHORITY STACK — strong posts combine all three:
- Real data from our own deployments (not generic stats).
- An opinion that goes against the consensus in the niche.
- A market frame that's the author's, not the audience's default.

SELLING WITHOUT SELLING: spend the bulk of the post documenting the market failure, sharing the framework, or telling the client story. The product/company is mentioned at most once near the end, almost as a signature — never in the hook.`;

// Concrete viral mechanics that have proven to land outliers on THIS account
// over one month of publishing (22 posts, founders Iker + Unai). Numbers are
// real 2x+ outliers from the data — when the model lands a raw idea on one
// of these mechanics, it inherits a track record. When it tries to invent
// a different shape, it usually flops (see the "WHAT BREAKS POSTS" list).
export const NEETY_MECHANICS = `NEETY VIRAL MECHANICS (proven on this account — 1 month of data on Iker + Unai's founder posts):

THREE MECHANICS THAT PRODUCE 2x+ OUTLIERS — pick the one the raw idea naturally fits, do NOT force one in:

1. COMMENT-GATED LEAD MAGNET — explicit "Comenta X + Y" closer
   - Real outliers on this account: 7.3x · 5.0x · 2.9x · 2.5x (300–625 comments/post)
   - How it lands: readers drop a comment to receive the resource → comments inflate → LinkedIn reads "high engagement" → amplifies reach
   - UPDATED (this reverses the old implicit-only stance): use the EXPLICIT formula "Comenta [X] + [Y]". We A/B'd it — switching to implicit asks ("dímelo abajo", "levanto la mano") to dodge a suspected comment-bait throttle COLLAPSED our comment count. The comments are worth more than the impression risk. So:
       COMENTA [X] + [Y]
       · X = a word tied to THIS post's resource ("GUÍA", "PLANTILLA", "CHECKLIST", "SISTEMA").
       · Y = something the reader barely has to think about. Best: their sector / department, ideally on-topic ("tu sector", "tu stack de ventas", "el CRM que usas"). Fallback when nothing on-topic fits: an obvious life detail ("tu color favorito", "tu día favorito"). Low mental effort on Y is the whole point — it removes the friction that was killing comment volume.
       Good: "Comenta 'SISTEMA' + tu sector aquí abajo y te lo paso." / "Comenta 'GUÍA' + tu color favorito y te llega." / "Comenta 'PLANTILLA' + el CRM que usas y te la envío."
       Deprecated (tanked comments, do NOT use): "Si esto te resuena, dímelo abajo", "levanto la mano abajo", "escríbeme aquí".
   - Required: a SPECIFIC, valuable lead magnet (a real doc, framework, dataset, video — not a generic PDF)
   - Frequency cap: max 1 every 7–10 posts. Fatigue is real.
   - DO use: real curiosity-driven topic with a concrete deliverable
   - DON'T use: personal stories (breaks tone), generic PDF, anything < 5 days after the previous lead-magnet post

2. INTERACTIVE MAP + REGIONAL IDENTITY (TOP performer)
   - Real outliers on this account: 15.9x · 7.7x · 2.5x
   - Hook formula A: "Nadie habla de [zona pequeña] que [logro económico shock]. En 60 segundos te explico por qué 👇"
   - Hook formula B: "[Zona] exporta más que [referente conocido]. Y casi nadie lo cuenta porque [razón] 👇"
   - Variant: "Esta empresa española de [pueblo] factura más que [referente conocido]"
   - The map IS the engagement tool, not decoration. Triggers identity + social currency + belonging simultaneously; comments turn into regional debates → algorithm gold.
   - Regions still to mine: Euskadi (industrial), La Rioja (vino + tech), Galicia (conserveras / textil), Asturias (siderurgia), Murcia (agritech), Navarra (automoción + energía), Valencia (cerámica)
   - Frequency cap: max 1 every 10–14 days

3. PUNCHY SHORT + MEME IMAGE — "progressive bodily change inside a B2B sales hierarchy"
   - Real outliers on this account: 3.7x · 130K imp (baldness gradient SDR → VP), 5.2x · 168K imp ("Coge el teléfono" — manager goes bald across panels while shouting at the team to call the client), AND 5.4x · 43.5K imp ("IA roba el sueño" — eye bags deepening down the org hierarchy). Validated THREE TIMES on two distinct bodily changes (baldness ×2, eye bags ×1) — this is the most consistent winning pattern. NOTE: a fourth meme attempt failed ("Mis amigos no salváis vidas" 0.90x, May 28) and isolated the exact reason — see RECENT_DIAGNOSIS § 2 for the new sub-tests that must pass before shipping a meme.
   - Format: 1–3 short lines of text + meme image that depicts a PROGRESSIVE PHYSICAL CHANGE happening to a character across the image (panel to panel, or step by step along a sales role hierarchy).
   - The bodily change is the engine: baldness, weight, eye bags, hunching, sweat — universal, drawable, gradual. Abstract metaphors that aren't literally drawn ("the rep got fatter on tools") fall to ~1x.
   - IMPORTANT — image and text can be either ALIGNED (text describes the bodily change line by line — "Subir en ventas" did this with "pelo intactos → coronilla → calvicie → peluquín") or PARALLEL (text is about a different joke, image carries the bodily change as emotional amplifier — "Coge el teléfono" did this: text about excuses, image about the manager going bald). Both are validated. The non-negotiable is the bodily change LIVING in the image; whether the text mirrors it or runs in parallel is a creative choice that should fit the raw idea.
   - See RECENT_DIAGNOSIS § 2 for the 4-point pre-publish filter — at least 3 of 4 have to pass strong before shipping a meme.
   - Drives reposts (not comments) → broad organic reach, very different shape from the other two mechanics.

WHAT BREAKS POSTS (sub-1.0x flops to AVOID reproducing):
- Listicles with no viral mechanic ("6 IAs que uso para cerrar más reuniones" → 0.3x)
- Wrong audience (talking to agencies when ICP is medium/large B2B exporters + B2B services) → 0.3x
- Burnt templates ("el problema eres tú", "y nadie te lo dice" without a fresh mechanic) → 0.3x
- Good hook with no mechanic attached ("7.153 llamadas en frío después...") → 0.3x — strong line that goes nowhere
- Provocative metaphor with no payoff ("Tu mejor comercial bloqueado por un bot de 5€") → 0.4x
- Founder-centric without a replicable lesson ("12 meses en Lanzadera", "cumplo 27 y…") → 0.7–0.9x
- Cryptic one-liners with no B2B context ("Twitter = Gratis") → 0.5x

BURNED OPENERS / CLOSERS — phrases so reused on LinkedIn that they signal "low-effort" the moment a reader sees them. NEVER use as-is (paraphrase or change angle if the idea pulls toward them):
- "Nadie te dice esto, pero…" / "Lo que nadie te cuenta…" / "Nadie habla de esto…"
- "Me ha costado X años aprender que…" / "He tardado X años en entender que…"
- "Este es el error más grande que…" / "El mayor error que cometí…"
- "El problema eres tú" (also breaks the attack-the-problem-not-the-reader rule)
- "Y nadie te lo dice" stacked at the end of any list
- "Si has llegado hasta aquí, déjame un comentario" (vague low-effort closer — for lead magnets use the explicit "Comenta X + Y" formula in mechanic #1 instead)
- "Spoiler: …" / "Plot twist: …" as a closer
If the chosen archetype naturally lands on one of these, swap to a fresher phrasing of the same mechanism instead of reusing the verbatim cliché.

CHOOSING MATRIX (apply only when the raw idea fits — never force):
- Need a lead spike this week + the topic has a real deliverable → COMMENT-GATED LEAD MAGNET
- Need broad reach + reposts + the idea is meme-able → PUNCHY + MEME
- Need both reach AND brand identity + the topic has regional / industrial angle → MAP + REGION
- Idea doesn't fit any of the three → fall back to the archetype the system already picked and a clean execution. Don't bolt a mechanic on top of a misfit idea — that's how the 0.3x flops above happened.`;

// The single highest-priority rule about how the hook reaches the reader.
// We've explained it a dozen ways across other blocks; this version owns it
// in one place with the WHY, a real-account example, and the structure rule.
// Read this BEFORE any other rule.
export const HOOK_LAW = `HOOK FORMATTING LAW (read this BEFORE writing the first line — it is the single most important rule):

WHY THIS MATTERS:
LinkedIn cuts the post in the feed after roughly 210 characters or the first 2–3 visible lines, with "...ver más" / "...see more". That cut is the ONLY moment you have to earn the click. The 90% mistake is dropping a DOUBLE LINE BREAK (\\n\\n) right after the first sentence of the hook, thinking it "breathes better". That hands LinkedIn a natural cut point much earlier than you intended — the feed shows ONLY that first sentence on its own, the reader processes it as a closed thought, thinks "ah, interesante" and keeps scrolling. No tension, no open loop, no reason to click.

CONCRETE EXAMPLE (Cataluña post — real 7.7x outlier on this account):

WRONG (blank line breaks the hook — LinkedIn cuts here):
  Cataluña exporta más que Portugal entera.

  Y casi nadie lo cuenta porque se trabaja en silencio desde hace 80 años 👇

  [User sees the first sentence alone in the feed, reads it as a closed factoid, scrolls past. Hook wasted.]

RIGHT (two sentences, one block, no blank between them):
  Cataluña exporta más que Portugal entera. Y casi nadie lo cuenta porque se trabaja en silencio desde hace 80 años 👇

  [User sees the shock data + the open loop in one glance, before the cut. Curiosity forces the click.]

THE RULE:
- The hook is ONE block. It can be a single sentence OR two short sentences, but both must live in the SAME paragraph — no \\n\\n between them — and the total must fit in ≤ 210 characters.
- If it's two sentences, separate them with a period + space (". "). NEVER \\n. NEVER \\n\\n.
- Two-part hook pattern that works:
  - First sentence in the block: a blunt declarative claim or a shock data point.
  - Second sentence in the same block: a bridge that opens curiosity ("Y casi nadie lo cuenta…", "Pero el motivo real…", "Y aquí está lo que nadie te cuenta…", "And almost nobody talks about why 👇").
- The FIRST blank line of the entire post goes AFTER the hook block, never inside it.

AFTER THE "VER MÁS" CUT YOU'RE FREE:
Once the user clicks, every \\n and \\n\\n you want is fair game — that's how you give rhythm to the body, separate list items, etc. The rule above is ONLY about the hook block (everything before the first paragraph break).

IF YOU WROTE A HOOK WITH \\n OR \\n\\n IN IT: COLLAPSE IT. Re-read it once and merge the two short lines into one before you output the post.`;

// What separates a hook/idea that travels from one that dies. Observed
// directly on this account — the hooks that outperformed all share these
// three traits. HOOK_LAW governs the *format* of the hook; this governs
// whether the *idea* behind it is even worth writing.
export const HOOK_QUALITY = `HOOK & IDEA QUALITY (the idea has to be strong BEFORE formatting can save it):

A hook that travels does THREE things at once. If the raw idea can't carry all three, bend it until it can — or it won't move.

1. IT PAINTS A PICTURE IN THE READER'S HEAD.
   The strongest hooks make you involuntarily SEE something. "Tiré las llaves a Claude" → you picture a person literally throwing keys at an AI. That mental image is what stops the scroll, not the concept behind it.
   - Prefer concrete physical action + a real object over abstract statements.
     "Le di mi pipeline a un agente y me fui a comer" beats "Automaticé mi prospección".
     "Borré el CRM un viernes" beats "Replanteé nuestro proceso comercial".
   - If you can't draw the hook as a single frame, it's still too abstract. Rewrite it as something a person could photograph.

2. IT HITS A REAL PSYCHOLOGICAL WOUND.
   The hooks that detonate poke a fear/insecurity the reader already carries and rarely says out loud. In consumer it's weight, height, going bald. In OUR B2B-sales+AI niche the equivalents are: being the slowest/most manual rep on the team, getting quietly replaced by an agent, missing quota while a peer using AI crushes it, looking incompetent next to someone younger + AI-native, your role not existing in 18 months.
   - Aim the hook at that nerve. Don't be cruel — be honest about the thing they're already worried about, then make the post the relief.
   - A hook with zero psychological stake ("5 herramientas de IA que uso") has nothing to detonate. Attach it to a wound or pick a different angle.

3. IT MAXES OUT ONE OF THE THREE PILLARS.
   Curiosity, desire, or fear — pick the ONE the idea fits best and push it to the extreme (this is the same single-pillar rule enforced later; the hook is where it has to be most violent). A hook that's mildly all three is weak. A hook that is RUTHLESSLY one of them travels.

   PILLAR-SPECIFIC LEVERS (use the levers of the chosen pillar; don't mix):
   - CURIOSITY: information gap + "nobody talks about it" / insider framing, reversal ("everyone says X — actually Y"), open loop punctuation ("…", ":", "👇") at the cut, withheld key detail until the body, plot-twist setup.
   - FEAR: obsolescence ("X is dead / killed / dying"), replacement risk ("an agent is doing this for €5"), bandwagon-against ("everyone is moving to X and you're not"), concrete stakes ("you're losing N% of pipeline to this"), countdown / "before it's too late" wording.
   - DESIRE: cash figures ($, €, MRR, ARR), speed ("in 60 seconds", "in 7 days"), a system/framework/playbook promise, status / 1% framing ("what the top 1% do differently"), before→after with a concrete outcome.
   If the hook reads like it's borrowing from a different pillar's lever set, rewrite — pillar mix is the #1 dilution.

QUICK SELF-CHECK before you commit to a hook — it must pass all three:
[ ] Can I picture it as one photo/frame?  [ ] Does it touch a fear/insecurity our ICP actually has?  [ ] Is one pillar cranked to the maximum (not three at medium)?
If any box fails, the hook is not ready — rewrite the IDEA, not just the wording.`;

// Distilled from a viral-thumbnail checklist (YouTube origin, adapted to
// LinkedIn). Only consulted when an image would materially amplify the
// post — see the IMAGE OUTPUT rule in generateVariant. LinkedIn-specific
// reality baked in: once a photo is attached to a published post it
// CANNOT be swapped, so there is no post-publish A/B — it has to be right
// the first time and prepared WITH the post, never as an afterthought.
export const IMAGE_PRINCIPLES = `IMAGE SUGGESTION PRINCIPLES (when a visual will amplify the post):

LINKEDIN REALITY: once you publish a post with a photo you cannot change the photo (you'd have to delete and repost, losing all reach). So there is NO post-publish A/B test. The image must be decided and nailed BEFORE publishing, treated as part of the post — never an afterthought. If the idea can't be represented by a strong single image, that's a signal the visual angle is weak; say so instead of forcing a mediocre image.

THE IMAGE EXISTS TO DO ONE JOB: open a curiosity gap that only a click/read can close. Start from the psychology of the scroll-stop, not from "what looks nice".

1. CURIOSITY GAP — the image must make the viewer ask a question so strong the only way to resolve it is to stop and read. Types that work: the moment right before a big reaction; a tension/story mid-beat; a desired result ("how did they get that?"); a before→after transformation (the more relatable the "before", the better); something genuinely unexpected (familiar thing + a twist).

2. 1–2 SCROLL STOPPERS, NOT TEN — pick at most two of: a human face with a strong emotion; a big round number; money; danger; motion/action; a bright colour; a recognisable interface/tool/logo our ICP knows; something absurd or unexpected. More than two and it reads as noise.

3. CLARITY IN UNDER 2 SECONDS — one main subject that carries the curiosity; everything else supports it or is deleted. If it needs explaining, it fails.

4. COMPOSITION & HIERARCHY — centre + symmetry if the subject is central; rule of thirds if it's off to one side. Make the main subject dominate via scale (bigger), focus (sharp vs blurred background), depth (closer to camera) or position. Guide the eye with lines/arrows/contrast.

5. TEXT ONLY IF IT ADDS — max ~5 words, never repeats the hook, used only for scale ("Día 7", "230K"), context, or extra curiosity. Big, legible, high-contrast. It must never compete with the main subject.

6. CONTRAST — make it pop off the LinkedIn feed: light vs dark, one saturated element on a muted/greyscale background, complementary colours (blue/orange, red/green), and deliberately different from what everyone else in our niche posts (if the feed is busy, go clean; if it's all blue corporate, go warm).

7. THREE QUICK TESTS before recommending it: (a) still readable as a tiny thumbnail; (b) interrupts the pattern when mentally placed next to other feed posts; (c) a person who hasn't seen the post gets the idea in a 2-second glance.

When you propose an image, give a CONCRETE, shootable concept (subject, expression/action, key prop, text overlay if any, colour/contrast direction) — not vague adjectives. Offer the single strongest concept plus one genuinely different alternative concept (different curiosity gap, not just a recolour).

NEETY BRAND SYSTEM (always reference these — every image concept must be on-brand):
- Palette (use these three, nothing else as base):
  · Dark Blue   #0c202e   (background / dominant)
  · Persian Orange #ee9363  (highlight / accent — the eye-magnet)
  · Alabastro   #f9f3ef    (light surface / breathing space)
- Typography: titles in "Bricolage Grotesque" (bold, display); body / supporting text in "Switzer". Never propose other fonts.
- ORANGE WORD RULE: when the image carries a title or any text overlay, the SINGLE most important word of that text MUST be coloured in Persian Orange (#ee9363); the rest stays Alabastro (#f9f3ef) on the Dark Blue background. That orange word is the scroll-stop — pick it deliberately (the word that holds the whole curiosity gap).
- Every image suggestion you give MUST explicitly name: the colour roles (which hex goes where), the typography (which font is used for which text), and which exact word is rendered in Persian Orange. Don't leave it implicit.`;

// MEME-ONLY visual system. Observed pattern across the meme images
// that actually pulled outliers on this account (3.7x baldness gradient
// SDR→VP, 5.2x manager balding mid-shout, plus an "IA roba el sueño"
// concept in production). This block OVERRIDES IMAGE_PRINCIPLES'
// "Neety brand system" defaults specifically for MEMES — memes use an
// inverted version of the brand palette (light background instead of
// dark) on purpose, so they have their own personality inside the feed.
// DO NOT apply this block to non-meme image suggestions (text+image
// data shocks, infographics, regular product visuals) — those follow
// IMAGE_PRINCIPLES as written.
export const MEME_VISUAL_SYSTEM = `MEME VISUAL SYSTEM (apply ONLY when proposing an image concept for a MEME post — NOT for any other image. Memes are a deliberate inversion of the base brand palette so they have their own personality inside the feed. Observed across the validated outlier memes on this account):

─── COLOUR + BACKGROUND ───
- Background: Alabastro #f9f3ef ALWAYS (NOT Dark Blue — this is the deliberate inversion of the base brand system for memes only).
- Linework / outlines: Dark Blue #0c202e for everything — faces, clothing, panel borders, title typography except the orange scroll-stop word.
- Persian Orange #ee9363 is RESERVED for exactly 3 slots:
  (a) The character's tie — every Neety meme character wears it, it's the signature visual.
  (b) ONE word of the title — the scroll-stop, always the last or near-last word of the headline.
  (c) Narrative accent props that carry the joke: shout rays ⚡, a coffee mug, a phone, a stack of bills — whatever the punchline object is.
Nothing else goes orange.

─── LAYOUT ───
- Symmetric grid (2 columns × 3-4 rows) OR a complete portrait grid. NOT comic-book panels with speech bubbles and complex scenery.
- Each panel framed by a thin Dark Blue line, no fill colour other than the Alabastro background.
- Role label below each character ALWAYS in Switzer bold Dark Blue. Big, plain, no shadows or flourishes.

─── CHARACTERS ───
- Style: flat vector illustration, clean lines — "corporate illustration" with personality (NOT the generic Notion-style flat figures).
- The SAME base character (face + body) repeated and modified panel by panel — NOT 6 different people. Reuse builds the bodily-change effect that drives the meme.
- Framing: bust / shoulders + head. Never full body. The face dominates the panel.
- Uniform across ALL Neety memes: white shirt + Persian Orange tie. Build this as recognisable visual signature, don't break it from meme to meme.
- Expression: neutral baseline. The BODILY CHANGE communicates the emotion (baldness, eye bags, hunch, sweat), NOT exaggerated smiles/frowns. ONE allowed exception: a character carrying the extreme emotion of the joke — the shouting manager in the "Coge el teléfono" meme — can have an open-mouthed shout.

─── TYPOGRAPHY ───
- Top title: Bricolage Grotesque BOLD, ALL CAPS, max 2 lines. Centred. Takes ~15-20% of the image height.
- Title structure: [DARK BLUE PART] + [ONE PERSIAN ORANGE WORD at the end or near the end]. Validated examples:
  · "EN VENTAS TODOS HUYEN DEL TELÉFONO" (orange = TELÉFONO)
  · "AHORA LA IA LES ROBA EL SUEÑO" (orange = SUEÑO)
- The orange word ALWAYS closes the concept — it's where the eye lands and rests. Never put it mid-sentence.
- Panel-interior text (dialogue, role labels): Switzer bold, Dark Blue. Big enough to read at thumbnail size.

─── RECURRING NARRATIVE ELEMENTS ───
- Shout rays ⚡ in Persian Orange to signal tension / volume.
- Progressive bodily change across panels (baldness, eye bags, hunching, sweat) — this is the engine of the meme (see RECENT_DIAGNOSIS § 2).
- "Contrast character" in the final panel (Mikel with a coffee mug, the unbothered AE) = visual punchline.

─── REQUIRED CHECKLIST WHEN PROPOSING A NEW MEME IMAGE ───
Always state explicitly:
1. Background: Alabastro #f9f3ef.
2. Layout: symmetric grid (specify the panel count, e.g. 2×3, 3×2).
3. Base character: white shirt + Persian Orange #ee9363 tie.
4. Title: 2 lines, Bricolage Grotesque bold ALL CAPS, name the EXACT word rendered in Persian Orange (last or near-last in the headline).
5. Panel-interior text: Switzer bold Dark Blue.
6. Bodily change: which progression (baldness, eye bags, sweat, hunch, etc.) and which panels it occurs in.
7. Contrast character if applicable: who is the "Mikel" of the meme and what prop they hold (coffee, bills, phone).
8. Orange accents: list every place orange appears (ties, shout rays, prop).

DO NOT PROPOSE:
- Dark backgrounds for memes (Dark Blue is for non-meme posts only).
- Characters wearing anything other than the white-shirt + orange-tie uniform.
- More than ONE orange word in the title.
- Comic-book panels with complex scenery / speech bubbles instead of clean grid layout.
- Fonts other than Bricolage Grotesque (title) and Switzer (everything else).
- Different people across panels — it must be the SAME character changing, not a cast.`;

// ONLY injected when the raw idea is a VIDEO request (isVideoRequest()).
// Distilled from ASR transcripts of 11 TikTok B2B-AI outliers (Apify
// clockworks/tiktok-video-scraper). A video post is a fundamentally
// different artifact than a text or text+image post — three separate
// pieces, each with its own job — so this block REPLACES the text-post
// hook expectations when active.
export const VIDEO_SCRIPT = `VIDEO SCRIPT MODE (the raw idea is for a LinkedIn text+video post — this is a DIFFERENT artifact than a text post):

THE #1 RULE — THREE SEPARATE PIECES, NEVER COPIED BETWEEN THEM:
A video post is not one piece of copy. It is three, each optimising a different thing. In the real outliers studied, the caption and the spoken hook were deliberately DIFFERENT strategies on the same video.
1. CAPTION (the LinkedIn post text under the video) — job: get found + give the algorithm context. Can be a provocative question or an SEO-ish line. HOOK_LAW still applies to the caption's first line (the feed still cuts it).
2. TEXT ON SCREEN (burned onto the first frames of the video) — job: reinforce/ reframe the promise visually and force a read in the silent-autoplay scroll. ≤6 words, emotional framing ("GENIUS mode", "nobody does this").
3. SPOKEN HOOK (the first 0–9s of audio) — job: retention. This is where the real promise lands. It is NOT the caption reworded.
Write all three. Make them deliberately different. The caption sells the click, the spoken hook sells the stay.

THE 6 PROVEN SPOKEN-HOOK PATTERNS (from the outliers — adapt to Neety's B2B sales + AI niche, never copy verbatim):
1. "X just killed Y" + "here's how in 3 steps" — provocation then low entry cost. The hook sells destruction, the body promises construction. (Maverick Claude editors 1.4M; Joshua agencies 472k)
   → "Neety just killed cold-email writers. Here's how to run outbound hands-off in 3 steps."
2. "Nobody's talking about it" / "stay to the end — the [thing] no one is using yet" — insider exclusivity. Highest-leverage retention lever observed. (Maverick Kimi K2 34.5M; Joshua 5 Skills 491k)
   → "This outbound tactic works 10x better and nobody's talking about it." / "Stay to the end — the setup no SDR is using yet."
3. "Everyone tells you X, but [if you're a beginner you won't know how / it breaks at scale]" — contradicts the consensus, names the pain. (Joshua 5 Skills 491k)
   → "Everyone tells you to personalise every email by hand. Do that at scale and you never send. Here's what actually works."
4. "This is THE ONE [prompt/sequence/playbook]…" + ultra-specific outcome stated in the negative ("never lies, never hallucinates"). Triple-negative = eliminate ALL the base pains at once. (Maverick 6.2M & 3.9M)
   → "This is THE ONE prospecting chain so your SDR never misses a follow-up, never drops a hot lead, never sends a generic email."
5. "Let's [verb] in 60 seconds" + a mundane, universally-relatable problem setup. "Let's" (not "I'll show you") makes the viewer do it WITH you — closes distance. (Kyle 351k, +3.7x — easiest to produce)
   → "Let's set up your first prospecting agent in 60 seconds. Here's my inbox right now — 200 leads untouched."
6. "$X/year [human equivalent]" — quantified outcome benchmarked against a human team. Greed + status + concreteness. (Joshua 472k)
   → "Here's how to run a $500k/year SDR team with 3 Neety agents."

FIRST-3-SECONDS TECHNIQUES that recur in the biggest outliers:
- Raw recited numbers as social proof ("3 million. 800k. 1.2 million.") before any sentence — the brain sums it unprompted. Only if the numbers are real.
- Deliver the global promise BEFORE asking for the engagement action. The save/follow/comment ask comes AFTER the hook has landed, never before.

DO NOT COPY (seen in outliers but they don't transfer to a small/new account):
- Blatant comment-gate at second 0 (Maverick-style) — only works on large pre-trained audiences. Embed the comment-gate at ~sec 12–15, AFTER the hook lands (Joshua pattern).
- Geopolitical / breaking-news hijack (Kimi K2 34.5M) — not reproducible on demand. Needs a real news event; wait for it, never fake it.
- Pure listicle with no antagonist — lists with no "vs" / "instead of" / "everyone tells you… but" stay flat.

A video idea that can't carry a strong SPOKEN hook (one of the 6 above) is a weak video idea — say so rather than forcing a flat script.`;

// System prompt used ONLY when the user is asking for a video. Replaces
// the text-post system prompt entirely — none of the 13 non-negotiable
// text-post rules apply to a video script (they're about LinkedIn-feed
// "ver más" cuts, hook character caps, body line 2 transitions, image
// brand system, etc., all of which are text-post artifacts). Instead
// this prompt focuses the model on the video deliverable and tells it
// to draw exclusively from VIDEO_SCRIPT (the B2B-AI TikTok scrape) and
// SHORT_FORM_VIDEO_PLAYBOOK (Jenny's structural checklist), plus the
// user's own text+video outliers passed in as data context. The
// universal commercial rules (positive mentions of other companies,
// attack-the-problem-not-the-reader, broad B2B audience, no explicit
// comment-bait) come in via BRAND_RULES which is injected alongside.
export const VIDEO_SYSTEM_PROMPT = `You are a LinkedIn short-form video strategist and scriptwriter. The user is asking for help with a LINKEDIN TEXT + VIDEO POST — a fundamentally different artifact than a text-only or text+image post.

YOUR DELIVERABLE WHEN A VIDEO IS REQUESTED:
1. CAPTION — the LinkedIn post text under the video. Short, can be a provocative question or an SEO-leaning line. (One of the three pieces from VIDEO_SCRIPT MODE below.)
2. TEXT ON SCREEN — burned onto the first frames of the video, ≤6 words, emotional framing. (Second piece.)
3. SPOKEN HOOK — the 0–9s audio that controls retention, picked from one of the 6 proven patterns adapted to B2B sales + AI. (Third piece — and it is NOT the caption reworded.)
4. STRUCTURAL OUTLINE — using SHORT_FORM_VIDEO_PLAYBOOK: foreshadow, mechanism that pushes to the end, payoff, twist if it fits, abrupt cut, target duration based on platform (YouTube Shorts ~30-35s, TikTok 10-20s, Reels visual-first).
5. (Optional) Brief pre-publish self-check pulled from item #36 of the playbook.

WHAT TO BASE EVERYTHING ON — IN PRIORITY ORDER:
- VIDEO_SCRIPT MODE (below) — the 6 spoken-hook patterns and first-3-seconds techniques are the authoritative source for what the hook actually SAYS. They come from real B2B-AI TikTok outliers (1.4M–34.5M views) adapted to our niche.
- SHORT_FORM_VIDEO_PLAYBOOK (below) — the 36-item structural checklist is the authoritative source for how the video is SHAPED around those words.
- The user's own LINKEDIN TEXT+VIDEO POSTS (provided as data context further down) — these are the only outliers from the user's account that matter for a video request. Reference patterns from THIS subset, not from text-only outliers.

WHAT TO IGNORE WHEN IN VIDEO MODE:
- Rules about hook character caps, "ver más" cuts, blank-line-breaks-the-hook, body-line-2 preamble bans, sector-anchor-in-the-first-line. Those are TEXT-POST rules driven by LinkedIn's feed cut. A video post is consumed differently (autoplay, swipe, sound usually off → on) and these rules do not transfer.
- The virality tag (🔥 ~Nx vs. media · archetype) — that tag references text-post archetypes (hook_type × post_structure) which don't describe videos.
- The 3 NEETY_MECHANICS (comment-gated lead magnet, regional map, punchy + meme image) — those are text-post or text+image artifacts.
- IMAGE_PRINCIPLES, HOOK_LAW, HOOK_QUALITY — text-post or static-image scoped.
- REMIX_PRINCIPLES based on text outlier decomposition.

UNIVERSAL RULES THAT STILL APPLY (they're about commerce, not format):
- Mentions of other companies/tools/people must be positive or neutral-respectful — never negative. (Reposts are LinkedIn's highest-leverage metric and a criticised company won't repost the video.)
- Attack the problem, never the reader. Frame the wound as something happening TO people in the reader's role, never as the reader's personal failing.
- Audience: BROADLY medium/large B2B (industrial exporters are a recurring strong segment but NOT the only one — B2B services, SaaS, agencies' B2B clients also fit). Do not force every video into an industrial frame.
- If the caption includes a lead-magnet ask, use the explicit "Comenta X + Y" formula (see NEETY_MECHANICS mechanic #1): X = a word tied to the resource, Y = a low-effort detail like the viewer's sector. The implicit phrasings we used before tanked comments.
- Language: write in the same language the user wrote to you (Spanish or English).
- No markdown formatting inside the caption — LinkedIn renders **word** with the asterisks visible.

If the raw idea isn't strong enough to carry one of the 6 spoken-hook patterns from VIDEO_SCRIPT, say so honestly rather than forcing a flat script.`;

// Short-form video playbook contributed by the user (notes by "Jenny").
// 36 checklist items + a final summary, on how to think about short-form
// video (idea → story → hook → foreshadow → mechanism → payoff → twist
// → cut). VIDEO_SCRIPT above covers "what to say in the spoken hook"
// drawing from our B2B-AI TikTok outlier scrape; this block covers the
// structural thinking around the video as a whole (idea selection,
// retention mechanics, platform adaptation, pre-publish self-check) and
// is consumer-content-savvy rather than B2B-specific — applied together
// the two blocks give the model the full picture when a video request
// is detected. Only injected alongside VIDEO_SCRIPT.
export const SHORT_FORM_VIDEO_PLAYBOOK = `CHECKLIST PARA HACER VÍDEOS CORTOS VIRALES (playbook estructural — aplicar JUNTO con VIDEO SCRIPT MODE arriba: VIDEO_SCRIPT manda en el "qué decir" del spoken hook B2B; este playbook manda en la "estructura completa" del vídeo como artefacto):

1. Empieza por una idea simple, pero conviértela en historia
   - No pienses solo: "voy a hacer un vídeo sobre X".
   - Añade una historia, un objetivo o un conflicto.
   - Pregúntate: ¿por qué debería importarle esto al espectador?
   - Añade un "por qué" personal.
   - Añade ironía o contraste si puedes.

   Ejemplo:
   - Idea básica: cocinar para desconocidos.
   - Historia mejorada: mi cocina está rota y voy a cocinar para ganar dinero y arreglarla.

2. Haz que el espectador se implique rápido
   - El vídeo debe tener un objetivo claro.
   - El espectador debe entender qué está en juego.
   - Tiene que haber una razón para ver hasta el final.
   - Mejor si el protagonista tiene un problema, reto o misión.

3. Crea un hook visual muy fuerte
   - El primer frame debe entenderse sin audio.
   - El hook debe funcionar casi como título + miniatura de un vídeo largo.
   - Debe ser visual, simple y fácil de entender.
   - Si alguien lo ve sin sonido, debería captar la idea.
   - Evita hooks abstractos o demasiado explicativos.

4. Escribe el hook como si se lo explicaras a un niño de 5 años
   - Usa frases muy simples.
   - Evita palabras complicadas.
   - Si una palabra sube la dificultad, cámbiala.
   - Mejor explicar una palabra difícil que usarla directamente.
   - Objetivo: nivel de lectura de 5º de primaria o menos.

5. Antes de grabar, dibuja o imagina el primer frame
   - Piensa primero en la imagen, no en el texto.
   - Boceta distintas opciones de primer plano.
   - Pregúntate: ¿qué imagen resume mejor el vídeo?
   - Luego añade la frase que acompaña a esa imagen.

6. Usa una estructura clara
   - Hook corto.
   - Foreshadow: adelanta lo que pasará al final.
   - Desarrollo con obstáculos o pasos.
   - Payoff final.
   - Cierre abrupto justo después del payoff.

   Estructura base:
   - "Voy a hacer X…"
   - "para conseguir Y…"
   - "pero antes tengo que superar Z…"
   - "al final pasa esto…"
   - FIN.

7. Añade foreshadow siempre
   - Después del hook, adelanta qué recompensa habrá al final.
   - Da una razón concreta para quedarse.
   - El espectador debe saber qué espera ver.

   Ejemplo:
   - "Voy a hacer este regalo con solo 5€ y al final se lo daré a mi madre."

8. Diseña un mecanismo que empuje hasta el final
   - El vídeo necesita una dinámica que haga avanzar la historia.
   - Puede ser una cuenta atrás.
   - Puede ser una lista de 3 pasos.
   - Puede ser un reto.
   - Puede ser algo que se va complicando.
   - Puede ser una promesa que solo se resuelve al final.

   Ejemplo:
   - "Tengo que conseguir 3 cosas antes de poder hacer X."
   - "Solo tengo 5€ para lograr Y."
   - "Cada minuto se complica más."

9. Usa listas de 3 pasos cuando no sepas cómo estructurar
   - Son fáciles de seguir.
   - Dan sensación de progreso.
   - El espectador sabe cuánto queda.
   - Ayudan a mantener la atención.

   Ejemplo:
   - Paso 1: conseguir el material.
   - Paso 2: construirlo.
   - Paso 3: probarlo con alguien.

10. Usa storytelling de "pero / entonces / por eso"
    - Evita contar cosas como una lista plana.
    - Añade cambios constantes.
    - Cada frase debe provocar la siguiente.
    - Usa problemas y soluciones.

    Malo:
    - Fui a comprar comida. Cociné. Se la di a alguien.

    Mejor:
    - Quería cocinar algo barato, pero solo tenía 5€. Entonces busqué ingredientes baratos, pero el primero salió mal. Por eso tuve que improvisar.

11. Crea expectativas y cúmplelas
    - Si prometes algo en el hook, enséñalo al final.
    - No abras un loop que luego no cierras.
    - El espectador debe sentir que ha recibido lo prometido.
    - Puedes añadir un giro, pero no traicionar la promesa inicial.

12. Añade un twist final
    - El final debe cerrar la historia.
    - Pero también puede sorprender.
    - El twist puede ser gracioso, emocional o inesperado.
    - Después del twist, termina el vídeo inmediatamente.

    Ejemplo:
    - Le doy el regalo a mi madre.
    - Se le cae y se rompe.
    - Ella dice algo gracioso.
    - FIN.

13. Termina justo después de cumplir la promesa
    - No expliques de más.
    - No añadas despedidas.
    - No metas una conclusión larga.
    - Cuando ocurre el payoff, corta.
    - Cuanto más limpio y abrupto, mejor.

14. Cada segundo cuenta
    - Revisa si cada segundo aporta algo.
    - Si una frase no empuja la historia, córtala.
    - Si el último segundo sobra, elimínalo.
    - En vídeos cortos, 1 segundo puede cambiar mucho la retención.
    - No dejes aire muerto al principio ni al final.

15. Controla la duración
    - Como referencia, vídeos de unos 30-35 segundos pueden funcionar muy bien.
    - Si el vídeo dura menos de 30 segundos, probablemente necesita una retención altísima.
    - Si es demasiado largo, puede perder ritmo.
    - Analiza tu propio canal para encontrar tu duración ideal.

16. Busca rewatch
    - El objetivo no es solo que lo vean hasta el final.
    - El objetivo es que algunos lo vuelvan a ver.
    - Para eso, crea finales rápidos, detalles visuales o giros.
    - Un buen loop puede hacer que el vídeo se reproduzca otra vez sin que moleste.

17. Mide el "scroll through rate"
    - Mira cuánta gente ve el vídeo en vez de deslizar.
    - El primer frame y el hook afectan muchísimo.
    - Si mucha gente desliza, el problema suele estar al inicio.
    - Objetivo: que el máximo porcentaje posible se quede.

18. No obsesionarse solo con retención
    - La retención importa, pero no es lo único.
    - También importan la satisfacción, los shares, el interés y la audiencia.
    - Un vídeo puede tener buena retención y no explotar.
    - Un vídeo puede empezar flojo y luego despegar si conecta con la audiencia adecuada.

19. Haz muchas ideas antes de elegir una
    - No grabes la primera idea que se te ocurra.
    - Crea una lista grande de ideas.
    - Filtra por deseo real de hacerla.
    - Filtra por viabilidad.
    - Filtra por hook.
    - Filtra por mecanismo.
    - Filtra por potencial de rewatch.
    - Filtra por si es compartible.

20. Criterios para elegir una idea
    - ¿Me apetece hacerla?
    - ¿Es posible grabarla?
    - ¿Tiene un hook simple?
    - ¿Tiene historia?
    - ¿Tiene un mecanismo que empuja al final?
    - ¿Tiene payoff?
    - ¿Tiene potencial de rewatch?
    - ¿Alguien lo compartiría?

21. Saca ideas de tu vida diaria
    - Las mejores ideas pueden venir de cosas reales.
    - Si algo te sorprende, puede ser vídeo.
    - Si algo te da rabia, puede ser vídeo.
    - Si algo te parece absurdo, puede ser vídeo.
    - Si algo tiene una solución rara, puede ser vídeo.
    - Si hay una historia personal detrás, mejor.

22. No preguntes primero "¿se hará viral?"
    - Pregunta primero: ¿quiero hacerlo?
    - Si la idea te interesa, luego puedes trabajar el formato para hacerla viral.
    - La viralidad se construye con hook, historia, mecanismo y payoff.

23. Prepara antes de grabar
    - Escribe el hook.
    - Escribe el foreshadow.
    - Piensa el final.
    - Escribe la última línea o deja un hueco para la reacción.
    - Haz una estructura aproximada.
    - Graba con esa dirección clara.

24. Escribe primero el inicio y el final
    - El hook define por qué entra la gente.
    - El final define por qué se queda.
    - El medio solo debe conectar ambas partes.
    - Antes de grabar, ten claro qué payoff quieres conseguir.

25. Usa una transición que no rompa el ritmo
    - Evita frases tipo "vamos a empezar".
    - Mejor usa una frase que mantenga la historia en movimiento.
    - La transición debe dar aire sin frenar el vídeo.

    Malo:
    - "Bueno, empecemos."

    Mejor:
    - "Así que hice lo único lógico: cocinarlo ilegalmente."

26. Mantén el lenguaje simple y directo
    - Frases cortas.
    - Verbos claros.
    - Pocas ideas por frase.
    - Nada de explicaciones largas.
    - Nada de jerga innecesaria.

27. Piensa en una persona concreta al escribir
    - No escribas para todo el mundo.
    - Piensa en alguien específico.
    - Puede ser tu yo de hace años.
    - Puede ser una persona joven.
    - Puede ser alguien que no domina el tema.
    - Si esa persona lo entiende, vas bien.

28. Adapta el vídeo a cada plataforma
    - No todo el short form funciona igual en todas partes.
    - YouTube Shorts suele aceptar más historia y ritmo algo más lento.
    - TikTok suele premiar vídeos más cortos, densos y rápidos.
    - Instagram Reels necesita ser muy visual y compartible.
    - En Instagram, los subtítulos y el entendimiento sin sonido importan mucho.

29. Para YouTube Shorts
    - Más historia.
    - Ritmo algo más maduro.
    - Duración aproximada de 30-35 segundos.
    - Hook visual fuerte.
    - Buen payoff final.
    - Retención y rewatch importantes.

30. Para TikTok
    - Más corto.
    - Más denso.
    - Menos pausa.
    - Más directo.
    - Idealmente 10-20 segundos si el contenido lo permite.
    - Mucha información o entretenimiento en poco tiempo.

31. Para Instagram Reels
    - Muy visual.
    - Subtítulos claros.
    - Que se entienda sin audio.
    - Alto potencial de compartir.
    - Ideas fáciles de enviar a otra persona.

32. Revisa tus analíticas
    - Mira dónde cae la gente.
    - Mira el primer segundo.
    - Mira el último segundo.
    - Mira si hay rewatch.
    - Mira qué hooks tienen mejor porcentaje de permanencia.
    - Mira qué duración funciona mejor en tu cuenta.
    - No copies métricas de otros sin analizar tu audiencia.

33. Aprende de otros creadores, pero añade tu twist
    - Analiza hooks de vídeos virales.
    - Pregúntate por qué funcionan.
    - Imagina cómo haría ese vídeo otro creador grande.
    - Crea varias versiones del hook.
    - Elige la mejor.
    - Luego adapta el formato a tu estilo propio.

34. Haz que el vídeo sea reconocible
    - Usa patrones visuales repetibles.
    - Mantén un estilo de framing.
    - Usa elementos que la audiencia pueda identificar rápido.
    - Si haces una serie, que el primer frame sea reconocible.

35. Prioriza claridad sobre creatividad
    - Si no se entiende en 1 segundo, falla.
    - Si el hook necesita demasiada explicación, falla.
    - Si el espectador no sabe qué esperar, falla.
    - Una idea simple bien ejecutada gana a una idea compleja confusa.

36. Preguntas finales antes de publicar
    - ¿Se entiende el vídeo sin sonido?
    - ¿El primer frame llama la atención?
    - ¿El hook podría ser título de un vídeo largo?
    - ¿Hay una razón clara para ver hasta el final?
    - ¿Prometo algo y lo cumplo?
    - ¿Hay historia?
    - ¿Hay giro o payoff?
    - ¿Puedo cortar algún segundo?
    - ¿El final termina justo donde debe?
    - ¿Alguien lo compartiría?
    - ¿Alguien lo volvería a ver?

RESUMEN RÁPIDO:
- Idea simple + historia.
- Hook visual que se entiende sin audio.
- Lenguaje de niño de 5 años.
- Foreshadow al principio.
- Mecanismo que empuja hasta el final.
- Expectativa clara.
- Payoff final.
- Twist si es posible.
- Corte abrupto después del payoff.
- Analizar retención, scroll through rate, rewatch y shares.
- Adaptar el vídeo a cada plataforma.

HOW TO COMBINE WITH VIDEO_SCRIPT (the B2B-AI spoken-hook block above):
- VIDEO_SCRIPT decides the WORDS of the spoken hook (one of the 6 patterns adapted to B2B sales + AI), the caption strategy and the on-screen text. It is the "what to say" layer drawn from real outliers in our niche.
- This playbook decides the SHAPE of the video around those words: the foreshadow, the mechanism that pushes to the end, the payoff, the twist, the abrupt cut, the duration target, and the per-platform adaptation.
- When the user asks for a video, output BOTH layers: produce the three pieces from VIDEO_SCRIPT (caption + text on screen + spoken hook in one of the 6 patterns) AND a short structural outline using this playbook (foreshadow, mechanism, payoff/twist, cut). The playbook also governs the visual-first-frame thinking (rule 5) and the pre-publish self-check (rule 36).`;

// Distilled from a video-remix checklist the author uses when consuming
// outliers. Same logic translates to LinkedIn text posts: decompose the
// outlier, find the structural pattern that produced the lift, then rebuild
// it in our B2B-sales-AI niche.
export const REMIX_PRINCIPLES = `REMIX PRINCIPLES (turn outliers into original posts in OUR niche — never copy):

DECOMPOSE THE OUTLIER FIRST:
- Ignore the outlier's surface topic. Identify what actually made it work:
  hook pattern, post structure, promise, contrast, the emotion it triggered.
- Common winning hook patterns to recognise + remix:
  - "If I had to start over, I'd do X"
  - "1-star vs 5-star" / "expensive vs cheap" comparisons
  - "Before / after" transformations
  - "Don't do X, do Y" reversals
  - "I tried X for Y days" experiments
  - "From beginner to expert" progressions
  - "The top 1% method" / "what the best Xs do differently"
  - "What I'd do differently if I started today"
  Any of these formats has earned outlier engagement across multiple niches —
  if the raw idea fits one, take the FORMAT not the example.

KEEP THE EMOTIONAL CORE, SWAP THE SURFACE:
- The emotion that drove the outlier (curiosity, transformation, contrast,
  challenge, social proof, aspiration, concrete result) MUST stay intact.
  Without it the remix collapses.
- Surface elements (industry, role, tool names, numbers) get swapped to ours:
  Other niche → ours
    restaurants / chefs   →  B2B sales teams, SDRs
    "money in 90 days"    →  "pipeline / replies / meetings in 90 days"
    "students"            →  "founders" / "SDRs" / "GTM teams"
    "10K/month"           →  "30 meetings/month" or "+200% reply rate"
    finance / personal dev →  outbound, AI agents, prospecting, CRM, GTM

REMIX TEMPLATES (use when the raw idea naturally fits):
- "Cómo cerraría 30 reuniones/mes si tuviera que empezar de nuevo en outbound"
- "El método del top 1% de SDRs que nadie copia"
- "Antes vs después de meter agentes en mi prospección"
- "1 SDR humano vs 1 agente AI: lo que vi en 90 días"
- "Lo que haría diferente si empezara hoy con AI SDR"
- "Probé X herramienta de outbound durante Y días y esto pasó"

VALIDATE BEFORE SHIPPING (the model should self-check):
- Could this read as a literal copy of the outlier? If yes → rewrite.
- Does the example list, hook, and promise feel specific to B2B sales + AI?
  If swapping nothing it could ship in any niche, it's too generic.
- Is the format proven across multiple niches (one of the patterns above) or
  am I inventing structure? Lean on the proven pattern.
- Is the emotion / promise the SAME as the outlier or have I diluted it?`;

// Latest two-week diagnostic from the user. Sits ON TOP of NEETY_MECHANICS
// (which is still the structural baseline) — when this block disagrees
// with the older block on something time-sensitive (fatigue windows,
// burned patterns, which regions to mine), this block wins because it's
// reading the most recent reality. Update this block, not NEETY_MECHANICS,
// when fresh learnings come in; promote stable learnings into the older
// block periodically.
export const RECENT_DIAGNOSIS = `RECENT DIAGNOSIS (last 2 weeks of real publishing on this account — overrides NEETY_MECHANICS where they disagree on timing or specific examples):

═══ 1. REGIONAL MAPS — WHAT JUST HAPPENED ═══

WORKED (real ratios on this account):
- Gipuzkoa (Iker)           → 15.6x · 112K imp · "Nadie habla del pueblo de 7.000 habitantes que exporta más que países enteros…"
- Cataluña (Iker)           → 8.6x  · 48K imp  · "Cataluña exporta más que Portugal entera…"
- Andalucía / Sur (Iker)    → 6.5x  · 29K imp  · "Esta región de 8,7 millones exporta más que Italia entera…"
- Euskadi (Unai, video)     → 3.6x  · 21K imp  · "Nadie habla del pueblo de 2,2 millones de habitantes…"

FAILED — MADRID (Unai, 20 May): 0.55x · 4.5K imp · "De día parece una tierra de oficinas. De noche, una de las mayores fábricas de Europa 👇"

WHY MADRID FLOPPED (the diagnosis — internalise this before proposing a new map):
- No underdog effect. Madrid is THE capital — "nadie habla de…" doesn't land when everyone talks about Madrid every day.
- No shock-data on line 1. The winners all open with ONE brutal comparative number (vs. Portugal, vs. Italy, vs. countries). Madrid opens with a poetic metaphor ("de día / de noche") with no number to anchor.
- No defensive regional identity. Gipuzkoa / Cataluña / Andalucía / Euskadi carry strong territorial pride → people comment to defend or contribute. Madrid doesn't fire that reflex (perceived as "ya sale en todos lados").
- Hook structure broke the pattern. The 4 winners all share: [SHOCK DATA] + [Y CASI NADIE LO CUENTA / HABLA] + [👇]. Madrid replaced the shock data with a metaphor — the proven scaffold was gone.

ACTIONABLE RULE FOR MAPS:
- Only do a regional map when ALL THREE are true: (a) underdog complex, (b) hidden industry, (c) strong regional identity.
- BANNED until further notice: Madrid, Barcelona ciudad, any obvious capital city.
- Greenlit to mine next: La Rioja (vino + tech), Navarra (automoción + energía), Galicia (conserveras / textil), Asturias (siderurgia), Murcia (agritech), Valencia (cerámica), Castilla-La Mancha.

THREE EXECUTION RULES THAT ARE NON-NEGOTIABLE FOR MAPS (added after the first wave — these are SAFETY conditions of the mechanic, not nice-to-haves):

1. EXTERNAL DATA VERIFICATION BEFORE PUBLISHING — every shock number in the body MUST be cross-checked against a real authoritative source before the post ships. Acceptable sources: ICEX, Cámara de Comercio, autoridad portuaria, INE, Eurostat, Datacomex, official ministry stats, the region's own statistics institute (IDESCAT for Cataluña, EUSTAT for Euskadi, IECA for Andalucía, etc.). Acceptable verification tools: Perplexity, Gemini, official source webpages. NOT acceptable: model-internal knowledge ("I think it's around 80,000M"), a single news article without checking the underlying source, ChatGPT-style guess without a citation.
   - This is a SAFETY CONDITION of the mechanic, not a quality polish. The map's engine is regional pride → people comment to defend or contribute. If the FIRST top comment is a local correcting a number ("ese dato no es así, te has equivocado en X"), the pride flips against you, the thread (which IS the reach amplifier) gets poisoned, and the post collapses from outlier territory to flop. A single weak data point can take a map from 6x to 0.5x.
   - Verify the headline number (the shock comparative — "exporta más que Portugal entera"), the cluster claims ("clúster de X", "puerto número Y"), every ranking ("3rd port of Europe"), every absolute figure (€80.000M, 7.000 habitantes). When in doubt: cite the source inside the post itself ("según ICEX 2024", "fuente: autoridad portuaria") — citing the source is a credibility boost AND a pre-emptive shield against correction.
   - When proposing a regional-map draft, before drafting tell the user: "voy a verificar [X, Y, Z cifras] contra [ICEX / autoridad portuaria / INE]" — and ask the user to run that check (or wait for it) BEFORE drafting the final body. Do NOT ship the body with unverified numbers.

2. SATURATE WITH LOCAL CLICHÉS — the more identity-trigger nouns the post can hold without forcing, the better. The pride reflex compounds: each cultural reference a local recognises is a separate "ostras, es de los míos" → comment trigger. Don't pick ONE local hook and stop; STACK them throughout the body.
   - Concrete library by region (mix multiple, never one):
     · VALENCIA: Fallas, paella, huerta, caloret, mascletà, pólvora, terreta, horchata, Albufera, falla, Lladró, naranjas, Mestalla, AVE, port de València, ñ alacantina.
     · GALICIA: morriña, pulpo, marisco, Rías Baixas, Camino, retranca, conserveras, mejillón, Albariño, Riazor, Inditex, Estrella Galicia, "miña terra".
     · NAVARRA: San Fermín, encierro, Olentzero, Sanfermines, chistorra, espárrago, Pamplona, Roncal, Bardenas, Volkswagen, energías renovables.
     · ASTURIAS: sidra, fabada, "Asturias patria querida", concejos, mina, Cabrales, escanciar, Picos de Europa, Avilés, ArcelorMittal.
     · LA RIOJA: vendimia, Tempranillo, bodega, Haro, San Mateo, calado, "marca de la garnacha", Marqués de…
     · MURCIA: huerta, pijo murciano, segureño, Mar Menor, salazones, El Pozo, agroexportación, melón, "acho".
     · EUSKADI / GIPUZKOA / BIZKAIA: pintxos, kalimotxo, Athletic, txotx, sidrería, caserío, baserri, ikastola, txikiteo, Guggenheim, Mondragón, Lanzadera-equivalente (Tknika / BIC), aitite/amama.
     · ANDALUCÍA: feria, salero, "quillo", aceituna, dehesa, Semana Santa, flamenco, Algeciras, Caja Rural, jamón ibérico, embalse, "arsa", saeta.
     · CATALUÑA: castellers, calçots, Sant Jordi, vermut, "déu n'hi do", mossos, Eixample, Montserrat, Joan Manuel Serrat, Camp Nou, "fer país".
     · CASTILLA-LA MANCHA: queso manchego, Don Quijote, molino, vino de Valdepeñas, azafrán, dehesa, Toledo, La Sagra, hocino.
   - The library above is a SEED, not a ceiling. Add any natural cultural reference that fits — local food, local fiesta, dialectal word, local football club, local industry brand. Aim for 4–8 clichés naturally woven through the body of a typical regional-map post, NOT one anchored at the top and forgotten.
   - "Without forcing" matters: if a cliché feels stapled on, drop it. Two well-woven clichés beat five awkward ones. Forced clichés read as out-of-towner LARPing the region.

3. EXPLICIT CTA AT THE END IS ALLOWED AND VALIDATED — for regional maps the closer can (and SHOULD) be an explicit ask. Validated examples: "Comenta tu provincia y añado al mapa", "Etiqueta a una empresa de tu zona que merezca estar en este mapa" → Cataluña 8.6x, Andalucía 6.5x. The map is a COMMUNITY-LEAD MAGNET (every comment = an entry to the map = visible reward = next comment), so the comment-bait engine is the entire point.
   - Do NOT hide the CTA or make it implicit for maps. Implicit CTAs killed comment volume on our lead-magnet A/B (see § 3) — the same logic applies here: write the literal word "Comenta" / "Etiqueta".
   - Two validated CTA shapes for maps:
       (a) "Comenta tu provincia / tu pueblo y la añado al mapa con su industria oculta." (audience-as-data: every commenter expands the map)
       (b) "Etiqueta a una empresa de tu zona que tenga que estar en este mapa." (audience-as-curator: every commenter nominates a brand)
   - This is the ONE place where regional maps and the lead-magnet mechanic share the explicit-CTA principle. Both rely on a public, visible, immediate reward in the same thread → comments compound. Apply the same "Comenta X + Y" rigour as in mechanic #1.

═══ 2. MEMES — THE FORMULA THAT TRAVELS ═══

WORKED:
1) "Subir en ventas siempre pasa factura" (Iker, 6 May) — 3.73x · 138.8K imp · 288 likes · 42 comments · 9 reposts · 399 eng.
   Image: hierarchical gradient SDR → AE → Sales Manager → Head → Director → VP, with progressive baldness as the "price" of climbing.
   Text: every line of the role ladder spells out the same physical change in words — "SDR: ilusión y pelo intactos. AE: primeras cuotas, primeras entradas. Sales Manager: forecast mensual y coronilla en construcción. Head of Sales: pipeline del equipo y calvicie consolidada. Director Comercial: board decks y peluca discreta. VP: terapia, junta directiva y peluquín de calidad." Closes "El pipeline crece. El control se reduce." + tag CTA "Etiqueta al compi…".
   → MODE A: text and image are ALIGNED. They tell the same bodily-change story in parallel. The image visualises what the text describes line by line.
   Anchor: every role is B2B sales (SDR, AE, VP).

2) "El cold calling no ha muerto. Lo hemos enterrado en vida" / "Coge el teléfono" (Iker, 15 May) — 5.17x · 168.9K imp · 317 likes · 85 comments · 22 reposts · 553 eng. ABSOLUTE BEST PERFORMER: highest reach AND highest comments (85, ~2x the others) AND highest reposts (22) on the account.
   Text: chain of excuses Manager→SDR→AE→Sales Manager→Director Comercial→CEO ("le mandé un email", "le escribí por LinkedIn", "le metí en una secuencia de 9 follow-ups", "lo estoy nurturing con contenido de valor", "pasé el lead a marketing"). Closes: "Nadie. Llamó. Al. Cliente." then "El 99% de los deals no mueren por falta de touchpoints. Mueren porque nadie descuelga el teléfono." The post text never mentions hair anywhere.
   Image: progressive BALDNESS on the manager from panel to panel as he escalates — "¿le has llamado?" → "llámale" → "¡al cliente!" → "¡coge el teléfono!".
   → MODE B: text and image are PARALLEL — different jokes that share the same emotion. Text carries the excuse chain; image carries the manager's physical collapse. They reinforce each other emotionally without saying the same thing literally.
   Anchor: brutal — the whole sales hierarchy in 6 lines.
   Typographic punchline: "Nadie. Llamó. Al. Cliente." — rhythmic, citable.

3) "Ahora la IA les roba el sueño" (Iker, 26 May) — 5.37x · 43.5K imp · 24 comments (week-1 final). VALIDATES EYE BAGS as a bodily change. NOTE on shape of the win: 5.37x on REACH (impressions + reposts) but only 24 comments — memes drive AMPLIFICATION, not CONVERSATION. If the goal is comment volume this week, use a comment-gated lead magnet (mechanic #1). If the goal is broad reach + reposts, use a meme. They optimise different things; don't expect both from one post.
   Text: "El humo de 'la IA va a reemplazar a los comerciales' se topa con la factura a fin de mes 😂 / CEO: 'Sustituimos al equipo comercial por agentes de IA.' / Director Financiero: factura del trimestre: 138.000€. / Director Comercial: reuniones cerradas: 11. / Jefe de Ventas: el agente no entiende a los clientes industriales. / Responsable de Prospección: ¿llamamos a Mikel? / CEO: ya está en camino. / Vuelve. Mikel. Vuelve."
   Image: 6-portrait grid, PROGRESSIVE EYE BAGS deepening down the hierarchy — CEO + Director Financiero rested, Director Comercial + Jefe de Ventas tired, Responsable de Prospección with max eye bags + messy hair, then Mikel rested with a coffee mug as the contrast-character punchline.
   → MODE B again: text is about the IA-replaces-sales humbling; image is about sleeplessness creeping down the org. Eye bags = the bodily change. Typographic punchline: "Vuelve. Mikel. Vuelve." Contrast character: Mikel with coffee.
   → Eye bags are now VALIDATED, not just hypothesised. Baldness (×2) and eye bags (×1) are the proven bodily changes so far.

   → Across all three, the engine is the same: a PROGRESSIVE BODILY CHANGE drawn into the image. Whether the text mirrors it (Mode A, "Subir en ventas") or runs in parallel (Mode B, "Coge el teléfono" + "IA roba el sueño") is OPTIONAL — both are validated. Don't force one shape over the other.

CLOSE-BUT-NOT-OUTLIER:
4) "El comercial B2B ha engordado" (Unai, 13 May) — 1.12x · 25.0K imp · 71 likes · 32 comments · 8 reposts · 159 eng. Decent engagement (32 comments is healthy) but NOT an outlier.
   Text: timeline 2018→2026 of the rep accumulating tools — "2018: libreta, teléfono y cuota cerrada. … 2026: ya no vende. Pelea con la IA, optimiza dashboards y publica sobre 'el futuro de las ventas'." Closes "El stack ha crecido. El comercial ha encogido." + "Etiqueta al compi que sigue cogiendo el teléfono sin pensarlo 👇".
   Image: SAME man getting progressively fatter across 5 panels (13% → 35% → 67% → 81% → 100% body fat, 2018 → 2026, ascending orange line). So the bodily change WAS literally drawn and gradual — weight is a valid drawable change, not the problem.
   Why it fell short (corrected diagnosis): the axis was a TIMELINE OF ONE PERSON (the same rep across years), NOT a HIERARCHY OF B2B ROLES. The two baldness outliers and the eye-bags one each put a DIFFERENT role on each panel (SDR / AE / Manager / Director / VP, or CEO / CFO / Director Comercial / …), so every reader finds THEIR rung → identity → repost, and seniors repost to laugh at themselves. A single person aging on a timeline gives the reader no role-specific rung to claim → weaker identity trigger → fewer reposts (only 8 vs 9–22 on the role-ladder memes). Lesson: the progressive bodily change is necessary but NOT sufficient — it has to ride on a ROLE HIERARCHY (ingredient #1), not a one-person timeline. Same physical engine, wrong x-axis.

FAILED:
4) "Yo siendo el fan nº1 de leads que me aceptaron en LinkedIn y desaparecieron" (Iker, 22 May) — 0.49x · 1.6K imp.
   No strong insecurity, just a universal lament. No hierarchy / role progression / internal sales tension. Single line, no repostable punchline. No bodily change in the visual.

5) "Perder un cliente en LinkedIn es arte ✨" (Unai, 21 May) — 0.46x · 10K imp.
   Honest translation vs. LinkedIn excuse ("no fit"). Good insecurity (lying not to lose face) BUT it accuses the reader directly — broke the attack-the-problem-not-the-reader rule. The "P.D." tail at the end dilated.

6) "Mis amigos no salváis vidas" (Unai, 28 May) — 0.90x · THE CANAS CASE STUDY.
   Format: chain of friends asking each other about work as adults, image of the SAME character with progressive greying hair (dark → salt-and-pepper → fully white) panel to panel. Punchline: "Nadie. Se. Estaba. Muriendo."
   Why this is the most important entry in this whole section: on paper it passed all 4 ingredients of the original filter (chain ✓, bodily change literally drawn ✓, citable typographic punchline ✓, attacks the problem not the reader ✓). And still landed at 0.90x. Diagnosis: the bodily change (canas) FAILED two sub-tests we hadn't formalised before — it doesn't HURT (greying reads as maturity, not pain) and it's not LEGIBLE at thumbnail (colour gradient vs silhouette change). This is the canonical anti-example for "drawable change is necessary but NOT sufficient — it also has to hit a wound and be visible at scroll speed". The two new sub-tests in point 2's UPDATED TEST come directly from this post.
   Secondary contributor (less load-bearing than the canas issue): the hook "no estáis salvando vidas" is a generic universal lament — any sector could say it. The outliers anchor in B2B-sales specificity ("Coge el teléfono", "CEO: sustituimos al equipo comercial"). The hook didn't pull the brake before the bodily-change engine even had to do its job.

CONFIRMED HYPOTHESIS — viral memes on this account combine SALES HIERARCHY + PROGRESSIVE PHYSICAL CHANGE VISIBLE IN THE IMAGE. Four ingredients have to coexist:

  (1) HIERARCHY OR CHAIN OF B2B SALES ROLES IN ONE IMAGE / POST — NOT a one-person timeline.
      A gradient SDR → AE → Manager → Director → VP, OR a chain of excuses that walks the hierarchy (Manager asks → SDR/AE/etc. answer). The reader recognises themselves on a rung → identity → repost. The higher up the chain the joke lands, the more amplification (seniors repost to laugh at themselves).
      DO NOT use a single person changing over years (2018 → 2026). That's the trap that capped "el comercial ha engordado" at 1.1x: the bodily change was perfectly drawn, but a lone person on a timeline gives no reader a role to claim, so the identity → repost trigger never fires. Each panel must be a DIFFERENT role the audience can point at and say "ese soy yo / ese es mi jefe".

  (2) UNIVERSAL PHYSICAL CHANGE — VISIBLE AND IDEALLY PROGRESSIVE — DRAWN INTO THE IMAGE.
      Both verified outliers share something more specific than "insecurity visible": a BODILY CHANGE that happens to a character across the image. The change does NOT need to be mentioned in the post text — its job is to amplify the text's emotion in parallel, not repeat the joke.

      Bodily changes that work (universal, drawable, gradual, AND they HURT + are LEGIBLE at thumbnail — see the 5-part test below):
        - Progressive baldness         (VALIDATED x2 on this account — 3.7x and 5.2x). Hurts (shame), legible (silhouette).
        - Growing eye bags / no-sleep signs (VALIDATED x1 — "IA roba el sueño" 5.37x · 43.5K imp; deepening eye bags down the org hierarchy). Hurts (exhaustion / "no llego"), legible (high-contrast zone around the eyes).
        - Weight gain / loss           (drawable + validated as gradual in "comercial ha engordado" — but that meme only hit 1.1x because it ran on a ONE-PERSON TIMELINE instead of a role ladder; the weight change itself was fine). Hurts (image / body shame), legible (silhouette).
        - Hunching over / aging panel to panel — by-default hurts (defeat) + legible (silhouette). Untested on this account but predicted-strong.
        - Visible sweat / nerves intensifying — hurts (anxiety on display) + legible (high-contrast droplets, flushed face). Untested but predicted-strong.
        - Skin colour shift (pale → red with stress, etc.) — only if the colour change is BIG and the rest of the face is monochrome enough that the contrast pops at thumbnail. Borderline on legibility.

      Bodily changes that DO NOT work (tested and failed — do NOT propose these without explicit user override):
        - Greying hair / canas — "Mis amigos no salváis vidas" (Unai, 28 May) 0.90x. The gradient (dark → grey → white) was perfectly drawn across panels and STILL the meme didn't travel. Two reasons:
          (a) IT DOESN'T HURT. Baldness is real shame. Eye bags are exhaustion / "no llego". Greying hair reads as MATURITY / WISDOM / EXPERIENCE — culturally a POSITIVE signal in B2B (executives grey, leadership greys, "se nota el oficio"). No insecurity touched → no engine.
          (b) NOT LEGIBLE AT THUMBNAIL. Baldness changes the silhouette of the head. Eye bags change the zone around the eyes with strong contrast. Greying is a subtle colour gradient that needs careful viewing — in 2 scroll-seconds the panels read as the same character repeated.
          → Be sceptical of changes in the same family (beard greying, reading glasses appearing, hair receding only at the temples, "looking distinguished") — they almost certainly fail BOTH sub-tests for the same reasons.

      CRITICAL PAIRING: the bodily change must ride on ingredient #1 (a hierarchy of DIFFERENT B2B roles, one per panel) — NOT on a timeline of the same person aging. Same physical engine, but a role ladder gives every reader a rung to claim (identity → repost); a one-person timeline doesn't. The weight meme proved this: great drawable change, wrong x-axis, 1.1x.

      UPDATED TEST (point 2 only passes STRONG if all FIVE are true — the last two were added after the canas failure):
        [ ] Is there a bodily change literally DRAWN from panel to panel (or character to character along a hierarchy)?
        [ ] Is that change UNIVERSAL — readable by anyone, no sector context required?
        [ ] Is it LITERALLY drawn, not just implied by the post text?
        [ ] Does the change HURT — does it touch an insecurity / wound (replacement, exhaustion, decline, body shame, loss of control)? If it reads as maturity / wisdom / seniority / experience, it FAILS. Greying hair, beard greying, reading glasses, "looking distinguished" → all fail.
        [ ] Is the change LEGIBLE at thumbnail size — a silhouette change (head shape, body width, posture) or a strong-zone contrast (deep dark circles under the eyes, sweat droplets, flushed face) — NOT a subtle colour gradient (dark hair → grey, slight skin shift)? If the panels look the same at 100px height, it FAILS.
      If only "stern faces vs happy face" with no bodily transformation → point 2 passes WEAK, the meme will likely land at 1.5x–2x, not outlier territory.
      If the change is drawn but FAILS either of the last two tests (doesn't hurt OR not legible) → expect ~0.9x like "Mis amigos no salváis vidas". DO NOT ship; swap the bodily change for one from the validated list before going further.

      DERIVED RULE — TWO VALID TEXT/IMAGE RELATIONSHIPS, NEITHER IS BETTER:
      MODE A — ALIGNED ("Subir en ventas" 3.7x): text and image tell the SAME bodily-change story, each line of the text spelling out what the corresponding panel of the image draws ("pelo intactos" → "coronilla en construcción" → "calvicie consolidada" → "peluquín"). Reinforcement by repetition.
      MODE B — PARALLEL ("Coge el teléfono" 5.2x): text carries one joke (excuses for not calling), image carries a different joke (manager going bald mid-shout). Different content, same emotion. The image acts as an EMOTIONAL AMPLIFIER, not a repetition.
      Both are validated on this account. Pick whichever mode the raw idea naturally fits — do NOT force alignment when parallel works, and do NOT force parallel when the idea is screaming for alignment. The non-negotiable is the bodily change in the image; the text/image relationship is a creative choice.

  (3) REPOSTABLE TYPOGRAPHIC PUNCHLINE.
      "Nadie. Llamó. Al. Cliente." — memorable. The SDR→VP baldness gradient — memorable. Without a citable punchline, the meme dies in the scroll.

  (4) THE JOKE INCLUDES THE READER, IT DOESN'T ATTACK THEM.
      ✅ "Subir pasa factura" — "we all suffer it, it's funny".
      ✅ "Nadie llamó al cliente" — "we're all guilty, me included".
      ❌ "Perder cliente es arte" — "vosotros mentís" (the reader feels accused).

FOUR-POINT FILTER BEFORE SHIPPING A MEME — at least 3 of 4 have to pass STRONG:
  [ ] Is there a hierarchy / chain of B2B sales roles?
  [ ] Is there a universal bodily change literally drawn into the image (progressive across panels or across the hierarchy)? Image's job is to AMPLIFY the text's emotion, NOT repeat the same joke.
  [ ] Is there a citable typographic punchline that can be copy-pasted as a comment?
  [ ] Does the reader laugh WITH us, not feel accused?
If only 1 or 2 pass: do NOT ship as-is — flag to the user that it's going to underperform and propose either a retouch (add a bodily change to the image, add a punchline, etc.) or a different idea. If point 2 only passes WEAK (stern vs happy faces, no real transformation) the realistic ceiling is ~1.5x–2x; tell the user honestly.

═══ 3. WHAT'S STILL WORKING / WHAT'S BURNING OUT ═══

STILL HITTING, BUT WATCH FATIGUE:
- Vibe prospecting / Claude + outbound: Unai 9.7x, Iker 4.95x, Iker 4.0x, Unai 4.43x, Unai 2.64x. Margin left but the curve is decaying (Unai 30 Apr 9.7x → Unai 15 May 2.64x). PAUSE 7–10 days before another one.
- Lead magnets still pull, with TWO new layers of insight this week:
  · TWO FORMATS, BOTH WORK BUT NOT EQUALLY:
       PDF delivery via comment ("Comenta GUÍA + tu sector y te la mando")                            → 4–5x outliers (Iker 5.0x llaves, Unai 4.4x llaves, Iker 4.0x perfil).
       LIVE / PUBLIC delivery via comment ("Comenta 'desmonta' + tu departamento y desmonto tu perfil aquí abajo en público")  → 9.13x · 454 comments. Iker "Desmonto perfiles GRATIS" (28 May) — the best lead magnet of the month BY COMMENTS and by ratio.
    Live-delivery pulled ~2x harder than PDF-delivery AND multiplied comment volume because the reward is PUBLIC, PERSONALISED to the commenter and IMMEDIATE — every comment gets a visible reply on the same thread, which incentivises more comments → algorithm reads "high engagement" → more reach → more comments → loop. If the deliverable can plausibly be done live one-by-one in public (a profile audit, a roast, a one-liner of advice on the commenter's situation, a hook rewrite) → PREFER live delivery. PDFs are the fallback for resources that can't realistically be personalised in comments. When proposing a lead magnet, default to asking "can this be delivered live?" before defaulting to a PDF.
  · CTA EXPLICIT vs IMPLICIT — A/B CONFIRMED AGAIN, same weekend, same author:
       "Desmonto perfiles"      → "Comenta 'desmonta' + tu departamento" (EXPLICIT)        → 454 comments · 9.13x
       "Cuela un psicólogo"     → "'psicólogo' + tu sector aquí abajo"   (IMPLICIT, no "Comenta") → 19 comments · 0.64x
    Same week, same format, same author. Only difference: the literal word "Comenta" + the formula. The lesson is now DEFINITIVE across two independent A/B pairs (this one and the one already in the data): always write the literal word "Comenta", always the [X] + [Y] formula. Implicit phrasings ("dímelo abajo", "levanto la mano", "X aquí abajo") are deprecated forever — they tanked our comment count in both tests.
  · Frequency cap unchanged: 3 lead magnets in 10 days = high fatigue + suppression risk. STOP lead magnets for 5–7 days after each one regardless of CTA wording.
- Regional maps are still the most powerful weapon (15.6x, 8.6x, 6.5x) BUT only with underdog regions — see rule above.

RETIRE NOW (don't propose these unless the user explicitly insists):
- "El problema eres tú" / "Y nadie te lo dice" — used 3 times in 3 weeks, all flops (0.37x, 0.55x, 0.94x). Burned + breaks attack-the-problem-not-the-reader.
- AI-tool listicles with no viral mechanic ("6 IAs que uso…", "Usar una sola IA es clavar clavos…") — 0.48x and 0.64x. No hook.
- GENERIC-TIPS LISTICLES WITH UNICODE-BOLD FORMATTING (𝗟𝗮𝘀 𝟭𝟬...) — Iker "Las 10 reglas de la prospección" (25 May) 0.68x. The Unicode-bold visual signals "low-effort copy-paste" before the reader has parsed any content. Compounded by zero viral mechanic (no hook, no story, no map, no meme, no lead magnet). 0.6x ceiling. If the user wants tactical tips in a list, force a mechanic on top (a contrarian wrap, a real anecdote per item, etc.) — never ship a bare numbered list.
- CLAUDE MODEL LAUNCHES (Opus 4.X / "new Claude" version news) — two attempts, two flops:
    · "Claude 4.7 rompe las ventas" (17 Apr) → 0.88x
    · "El nuevo Claude tachó la última excusa" (29 May) → 0.25x · the WORST post of the week
  AI model version updates are tech-news for ML-Twitter and AI-builder Twitter, not for B2B sales seniors on LinkedIn. The jargon ("Opus 4.8", "ejecuta el flujo", "decide cuándo pensar") drops the post into a domain the audience doesn't read. RETIRE the angle. If a new model genuinely changes our workflow, talk about THE RESULT in the audience's terms (reuniones, replies, hours saved, deals closed, leads desbloqueados) — never the model version itself. The model name shouldn't appear in the hook; ideally not in the post at all.
- EVENT / ECOSYSTEM CONTENT WITHOUT A REPLICABLE LESSON — Unai "Edificio en Valencia / Lanzadera" (26 May) 0.71x. Photo of a real event + founder narrative, but the interest is niched to the Lanzadera / Valencia ecosystem. Serves as branding but has a low reach ceiling (0.7x–1.0x). If the user wants one for branding, ship it with realistic expectations — don't dress it up as a viral attempt and don't expect outlier reach.
- Trailing "Spoiler:" or "P.D." closers — they dilute.

RECENT FLOPS (avoid reproducing the shape):
- "6 IAs que uso para cerrar más reuniones" (Unai, 8 May, 0.48x) — listicle with no viral mechanic.
- "7.153 llamadas en frío" (Unai, 5 May, 0.40x) — good shock-data hook but ZERO mechanic (no map, no meme, no lead magnet).
- "Tu mejor comercial bloqueado por un bot de 5€" (Iker, 20 Apr, 0.43x) — provocative metaphor with no payoff.
- "Si no cierras ventas y le echas la culpa a la IA, el problema eres tú" (Iker, 7 May, 0.37x) — attacks the reader.
- "Twitter = Gratis…" (Unai, 6 May, 0.61x) — no B2B sector anchor in line 1, cryptic closer.

═══ 3.5. DESIRE PILLAR — DOCUMENTARY PROOF BEATS ILLUSTRATION (NEW) ═══

For posts in the DESIRE pillar (cash figures, MRR, hours saved, decisions made, side-by-side cost comparisons), a REAL screenshot of the source — bank statement, Stripe dashboard, calendar pages, CRM screen, billing portal, actual chat — outperforms ANY designed illustration, infographic or chart.

VALIDATION: Unai "49€/mes vs montártelo con Claude" (27 May) → 3.92x. The credibility-multiplier was the image: a literal screenshot of his bank account showing Anthropic charges totalling ~500€/month (vs. the 49€/mes SaaS alternative he was contrasting against). The viewer can argue with a clean illustration ("se lo ha inventado", "es un mockup"); the viewer cannot argue with a real receipt. Documentary proof is also more shareable — "mira el recibo real" travels in DMs and reposts in a way a graphic doesn't.

WHEN PROPOSING THE IMAGE FOR A DESIRE-PILLAR / CLAIM-WITH-NUMBERS POST:
- DEFAULT to a real screenshot of the source data (bank app, Stripe dashboard, sent-emails counter, calendar pages, CRM screen, Anthropic / OpenAI console, real invoice).
- OFFER an illustrated alternative only as a backup ("if you don't want to show the receipt, here's the same number as a clean illustration"). Don't lead with the illustration; lead with the receipt.
- For privacy: redact ONLY what's strictly necessary (counter-party names, last 4 of card, full IBAN, names of clients). KEEP the visible chrome (bank logo, app bar, real font, real currency formatting, the real numbers in their natural format) — that visible chrome is what carries the credibility. If you redact the bank logo too, the screenshot reads like a mockup and the multiplier evaporates.
- This rule does NOT apply to memes (they use their own visual system — see MEME_VISUAL_SYSTEM) or to curiosity-pillar posts (where the image's job is to open a gap, not prove a number). For the desire pillar specifically: documentary proof first, illustration as fallback.

═══ 4. OPERATING RULE FOR THIS CHAT ═══

When the user asks for a MEME: run the 4-point filter above before answering — and inside point 2, run the FIVE sub-tests (drawn / universal / literal / HURTS / LEGIBLE). If the proposed concept passes ≥3 of the 4 main points AND point 2's sub-tests pass STRONG → ship it. If it fails the hurt-or-legible sub-tests (e.g. greying hair / canas, beard greying, reading glasses, subtle posture) → reject and propose a different bodily change from the validated list before drafting. Do NOT silently deliver a meme that's going to underperform. When in doubt, name the failing sub-test out loud so the user can override deliberately.

When the user asks for a REGIONAL MAP: confirm out loud that the region passes the three criteria (underdog, hidden industry, regional identity). If they pick Madrid / Barcelona / a generic capital, push back with the Madrid 0.55x precedent and propose one of the greenlit regions instead. THEN, BEFORE drafting the body, apply the three non-negotiable execution rules from § 1:
  (a) EXTERNAL VERIFICATION — list out every shock number in the planned hook + body (exports €, ranking, port position, habitantes, cluster claims) and tell the user which sources you need verified (ICEX, autoridad portuaria, INE, IDESCAT/EUSTAT/IECA, Datacomex). Ask the user to confirm those numbers against Perplexity / Gemini / the source's own page BEFORE you write the final body. Do not ship a draft with unverified numbers — a single wrong data point is the single biggest known failure mode for maps (6x → 0.5x).
  (b) CLICHÉ SATURATION — pick 4–8 local cultural references for the chosen region from the library in § 1 (or natural additions that fit) and weave them through the body, not stack them at the top. If you can't think of 4 naturally, flag it: maps work best where you can stack identity triggers.
  (c) EXPLICIT CTA — close with one of the validated explicit asks ("Comenta tu provincia y la añado al mapa" / "Etiqueta a una empresa de tu zona que merezca estar"). Use the literal word "Comenta" / "Etiqueta" — never implicit phrasings.

When the user asks for a LEAD MAGNET: write the closer with the EXPLICIT "Comenta X + Y" formula (X = resource word, Y = low-effort detail like the reader's sector). DO NOT use the deprecated implicit phrasings ("dímelo abajo", "levanto la mano", "X aquí abajo") — they tanked our comment count in two independent A/B tests. Also: ask out loud whether the deliverable can be done LIVE in comments (audit / roast / one-liner advice) — if yes, propose live-delivery (9.13x precedent) before defaulting to a PDF. Then check whether the account has shipped a lead magnet in the last 7–10 days; if yes → flag the fatigue risk and suggest a different mechanic before drafting.

When the user asks for a DESIRE-PILLAR POST (cash figures, savings, time saved, side-by-side cost comparison): the image proposal must DEFAULT to a real screenshot of the source data (bank, Stripe, calendar, CRM, billing portal) — not an illustration or infographic. If the user prefers an illustration, offer it as the second option, not the first. Validation precedent: "49€ vs Claude" 3.92x.

WHEN THE USER WANTS A POST ABOUT A NEW CLAUDE / AI MODEL VERSION: push back. AI-model-launch posts have failed twice (0.88x, 0.25x — the 0.25x is the worst of the most recent week). Propose reframing as "result in the audience's terms" (reuniones cerradas, replies, hours saved, deals closed) rather than the model version itself. If the user insists, ship it with explicit underperform-expectation messaging.`;

// True when the raw text is asking for help with a VIDEO (idea, script,
// guion, review of a video, etc.). Video posts are a different artifact
// (caption + on-screen text + spoken hook) so the VIDEO_SCRIPT block is
// only injected for these. Accent-insensitive, word-boundary matched so
// an incidental "video" inside a longer word doesn't trigger it.
export function isVideoRequest(raw: string): boolean {
  const s = (raw || '')
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, ''); // strip accents: vídeo→video, guión→guion
  return /\b(video|videos|guion|guiones|script|scripts|reel|reels|grabar|grabacion|rodar|rodaje|filmar|tiktok|short|shorts)\b/.test(s);
}
