import { Router, Request, Response } from 'express';
import Anthropic from '@anthropic-ai/sdk';
import { PostIdeaModel } from '../models/postIdea';
import pool from '../db';
import { ensureSingleLineHook } from '../utils/sanitizeText';

const router = Router();
const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

function paramId(req: Request): string {
  return req.params.id as string;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

// Human-readable labels for hook/structure archetypes
const HOOK_LABELS: Record<string, string> = {
  pattern_interrupt: 'Ruptura de patrón', belief_breaker: 'Rompe creencias',
  curiosity_gap: 'Intriga', data_shock: 'Dato impactante', hot_take: 'Opinión polémica',
  personal_confession: 'Confesión personal', story_opener: 'Apertura narrativa',
  hypothetical_question: 'Pregunta hipotética', why_question: 'Pregunta "por qué"',
  how_question: 'Pregunta "cómo"', direct_question: 'Pregunta directa',
  bold_claim: 'Afirmación audaz', common_mistake: 'Error frecuente',
  direct_callout: 'Llamada directa', list_promise: 'Promesa de lista',
  contrarian_take: 'Contrarian', relatable_moment: 'Momento relatable',
  motivational: 'Motivacional', observation: 'Observación', other: 'Otro',
};
// Hard rules baked into every post generated by the Post Creator. These
// reflect commercial reality, not stylistic preferences:
// - LinkedIn distribution favours reposts above any other engagement metric;
//   a company that gets criticised in your post will never repost it, so the
//   downside vs. the upside is heavily asymmetric. Frame any mention positive.
// - Neety's current ICP is medium/large industrial exporters and B2B service
//   companies. When the model has freedom to choose examples or audience
//   framing, it should default to those.
const BRAND_RULES = `BRAND & AUDIENCE RULES (non-negotiable):
- NEVER criticise, mock, or speak negatively about any other company, brand or competitor by name. If a company is mentioned, the framing MUST be positive or neutral-respectful. Reposts are the highest-leverage LinkedIn metric and a criticised company won't repost — the upside of a sharp jab almost never beats the lost reach.
- If you need a counter-example, talk about a generic pattern ("most CRMs", "the average outbound playbook") rather than naming a specific company.
- Neety's ICP is medium/large INDUSTRIAL companies that export and B2B SERVICE companies. When you have latitude on examples, audience framing or pain points, default to those segments.`;

// Pulled from 2 weeks of real publishing data on this account. These complement
// the global outlier pool — they tell the model which patterns produced reposts
// and saves for THIS specific account vs which fell flat. Treat as a heavy
// prior on top of the archetype.
const CREATOR_LEARNINGS = `CREATOR LEARNINGS (from 2 weeks of real publishing on this account — apply on top of the archetype):

LEAN HARD INTO (top performers, e.g. 20x outliers):
- "Insight + hidden system + contrarian": show how something actually works behind the scenes — a mechanic, an incentive, a distribution rule, a pattern that most people in the audience don't see. Pair with concrete data when possible.
- Break the reader's default belief inside the first 1–3 lines. The hook should make them think "wait, that's not how I thought it worked".
- Mix data WITH narrative. A specific number anchored in a story beats either pure data or pure story.

ACCEPTABLE BUT WEAKER (use only when the raw idea genuinely fits):
- Pure provocation + universal-problem framing (e.g. "lead-magnet prospecting messages"). Drives comments but lower repost rate.

NEVER PRODUCE:
- Generic posts that ANY creator in the niche could publish. If swapping the author name wouldn't change the content's credibility, the post is too generic — rewrite it with a hidden-system angle or a specific anecdote.
- AI-news recaps without the author's own framing or hidden insight on top.
- Opinions with no proof: claims that aren't backed by a number, a specific anecdote, or a named case.
- "Personal" posts without an edge (birthday/gratitude/milestone with no sharp lesson). If the post is personal, it must contain a concrete takeaway the reader can use.

THE WIN/LOSE TEST: a post WINS when it (a) explains how a system actually works AND (b) breaks a commonly held belief. A post LOSES when it reads like it could've been ghostwritten for any creator in the niche.`;

// Distilled from a research pass over ~45 top-performing B2B AI / sales
// founders on LinkedIn (EN + ES). These are the structural moves that
// separated 60-1.000+ like posts from generic noise. Treat as a heavy prior
// the model can apply whenever the raw idea has latitude — without forcing
// the framing if the idea genuinely doesn't fit.
const POSITIONING_PRINCIPLES = `POSITIONING PRINCIPLES (research-backed — apply whenever the raw idea has latitude):

THE 5 LEVERS:
1. Position by CONTRAST, not features. "Most teams do X. We do Y because Z" outperforms "We do Y very well". Lead by naming what's broken in the default playbook before saying what we do.
2. Client numbers beat self-praise. "+200 PYMES, +40% conversion" lands harder than "best AI sales platform". When a real client metric exists, use it.
3. Lead with a market frame, not a product feature. Recurring contrasts like "operativa vs. operacional", "agentic vs. tool", "signal vs. cold volume", "ejecución vs. gestión" carry the post; bare feature descriptions read as ad copy.
4. Reuse one concept word that's ours. A single term repeated across posts builds a category in the reader's head.
5. Founder name > product name. The post sells the thinker; mention the product at most once near the end, not in the hook.

5 HIGH-CONVICTION POST PATTERNS — pick one when the raw idea genuinely fits:
- Anti-consensus on a hot category. "Everyone's launching AI SDRs. Most are flopping. Here's what actually moves outbound."
- Founder microstory with a specific moment. "Closed a customer at 18:02 on a Saturday. No human would have. The agent did."
- Numbered workflow with concrete tool stack. "Agent 1 captures X. Agent 2 enriches Y. Agent 3 decides Z." Each step has a real output.
- Market thesis with hard numbers (CAC, reply rate, ARR comps) the reader can't easily argue with.
- "Deciding in public" — "Considering X vs Y for [decision]. Trade-off as I see it: [...]. What would you do?"

AUTHORITY STACK — strong posts combine all three:
- Real data from our own deployments (not generic stats).
- An opinion that goes against the consensus in the niche.
- A market frame that's the author's, not the audience's default.

SELLING WITHOUT SELLING: spend the bulk of the post documenting the market failure, sharing the framework, or telling the client story. The product/company is mentioned at most once near the end, almost as a signature — never in the hook.`;

// Concrete viral mechanics that have proven to land outliers on THIS account
// over one month of publishing (22 posts, founders Iker + Unai). Numbers are
// real 2x+ outliers from the data — when the model lands a raw idea on one
// of these mechanics, it inherits a track record. When it tries to invent
// a different shape, it usually flops (see the "WHAT BREAKS POSTS" list).
const NEETY_MECHANICS = `NEETY VIRAL MECHANICS (proven on this account — 1 month of data on Iker + Unai's founder posts):

THREE MECHANICS THAT PRODUCE 2x+ OUTLIERS — pick the one the raw idea naturally fits, do NOT force one in:

1. COMMENT-GATED LEAD MAGNET — CTA "comenta '<keyword>' y te mando el <recurso>"
   - Real outliers on this account: 7.3x · 5.0x · 2.9x · 2.5x (300–625 comments/post)
   - How it lands: the CTA inflates comments → LinkedIn algorithm reads "high engagement" → amplifies reach
   - Required: a SPECIFIC, valuable lead magnet (a real doc, framework, dataset, video — not a generic PDF)
   - Frequency cap: max 1 every 7–10 posts. LinkedIn is starting to penalise comment-bait; fatigue is real.
   - DO use: real curiosity-driven topic with a concrete deliverable
   - DON'T use: personal stories (breaks tone), generic PDF, anything < 5 days after the previous lead-magnet post

2. INTERACTIVE MAP + REGIONAL IDENTITY (TOP performer)
   - Real outliers on this account: 15.9x · 7.7x · 2.5x
   - Hook formula A: "Nadie habla de [zona pequeña] que [logro económico shock]. En 60 segundos te explico por qué 👇"
   - Hook formula B: "[Zona] exporta más que [referente conocido]. Y casi nadie lo cuenta porque [razón] 👇"
   - Variant: "Esta empresa española de [pueblo] factura más que [referente conocido]"
   - The map IS the engagement tool, not decoration. Triggers identity + social currency + belonging simultaneously; comments turn into regional debates → algorithm gold.
   - Regions still to mine: Euskadi (industrial), La Rioja (vino + tech), Galicia (conserveras / textil), Asturias (siderurgia), Murcia (agritech), Navarra (automoción + energía), Valencia (cerámica)
   - Frequency cap: max 1 every 10–14 days

3. PUNCHY SHORT + MEME IMAGE
   - Real outlier on this account: 3.7x with 130K impressions (highest reach of the month)
   - Format: 1–3 short lines of text + meme image carrying an uncomfortable truth with humor
   - The IMAGE carries 80% of the message; the text only activates it. This won't work as text-only — only pick this mechanic when the idea is genuinely meme-able and there's a visual to ship.
   - Drives reposts (not comments) → broad organic reach, very different shape from the other two

WHAT BREAKS POSTS (sub-1.0x flops to AVOID reproducing):
- Listicles with no viral mechanic ("6 IAs que uso para cerrar más reuniones" → 0.3x)
- Wrong audience (talking to agencies when ICP is medium/large B2B exporters + B2B services) → 0.3x
- Burnt templates ("el problema eres tú", "y nadie te lo dice" without a fresh mechanic) → 0.3x
- Good hook with no mechanic attached ("7.153 llamadas en frío después...") → 0.3x — strong line that goes nowhere
- Provocative metaphor with no payoff ("Tu mejor comercial bloqueado por un bot de 5€") → 0.4x
- Founder-centric without a replicable lesson ("12 meses en Lanzadera", "cumplo 27 y…") → 0.7–0.9x
- Cryptic one-liners with no B2B context ("Twitter = Gratis") → 0.5x

CHOOSING MATRIX (apply only when the raw idea fits — never force):
- Need a lead spike this week + the topic has a real deliverable → COMMENT-GATED LEAD MAGNET
- Need broad reach + reposts + the idea is meme-able → PUNCHY + MEME
- Need both reach AND brand identity + the topic has regional / industrial angle → MAP + REGION
- Idea doesn't fit any of the three → fall back to the archetype the system already picked and a clean execution. Don't bolt a mechanic on top of a misfit idea — that's how the 0.3x flops above happened.`;

// Distilled from a video-remix checklist the author uses when consuming
// outliers. Same logic translates to LinkedIn text posts: decompose the
// outlier, find the structural pattern that produced the lift, then rebuild
// it in our B2B-sales-AI niche.
const REMIX_PRINCIPLES = `REMIX PRINCIPLES (turn outliers into original posts in OUR niche — never copy):

DECOMPOSE THE OUTLIER FIRST:
- Ignore the outlier's surface topic. Identify what actually made it work:
  hook pattern, post structure, promise, contrast, the emotion it triggered.
- Common winning hook patterns to recognise + remix:
  - "If I had to start over, I'd do X"
  - "1-star vs 5-star" / "expensive vs cheap" comparisons
  - "Before / after" transformations
  - "Don't do X, do Y" reversals
  - "I tried X for Y days" experiments
  - "From beginner to expert" progressions
  - "The top 1% method" / "what the best Xs do differently"
  - "What I'd do differently if I started today"
  Any of these formats has earned outlier engagement across multiple niches —
  if the raw idea fits one, take the FORMAT not the example.

KEEP THE EMOTIONAL CORE, SWAP THE SURFACE:
- The emotion that drove the outlier (curiosity, transformation, contrast,
  challenge, social proof, aspiration, concrete result) MUST stay intact.
  Without it the remix collapses.
- Surface elements (industry, role, tool names, numbers) get swapped to ours:
  Other niche → ours
    restaurants / chefs   →  B2B sales teams, SDRs
    "money in 90 days"    →  "pipeline / replies / meetings in 90 days"
    "students"            →  "founders" / "SDRs" / "GTM teams"
    "10K/month"           →  "30 meetings/month" or "+200% reply rate"
    finance / personal dev →  outbound, AI agents, prospecting, CRM, GTM

REMIX TEMPLATES (use when the raw idea naturally fits):
- "Cómo cerraría 30 reuniones/mes si tuviera que empezar de nuevo en outbound"
- "El método del top 1% de SDRs que nadie copia"
- "Antes vs después de meter agentes en mi prospección"
- "1 SDR humano vs 1 agente AI: lo que vi en 90 días"
- "Lo que haría diferente si empezara hoy con AI SDR"
- "Probé X herramienta de outbound durante Y días y esto pasó"

VALIDATE BEFORE SHIPPING (the model should self-check):
- Could this read as a literal copy of the outlier? If yes → rewrite.
- Does the example list, hook, and promise feel specific to B2B sales + AI?
  If swapping nothing it could ship in any niche, it's too generic.
- Is the format proven across multiple niches (one of the patterns above) or
  am I inventing structure? Lean on the proven pattern.
- Is the emotion / promise the SAME as the outlier or have I diluted it?`;

const STRUCT_LABELS: Record<string, string> = {
  hook_list_cta: 'Hook → Lista → CTA', hook_story_lesson_cta: 'Historia → Lección → CTA',
  problem_agitate_solve: 'Problema → Agitación → Solución',
  contrarian_proof_reframe: 'Contrarian → Prueba → Reencuadre',
  confession_insight_takeaway: 'Confesión → Insight → Conclusión',
  list_framework: 'Framework en lista', problem_solution: 'Problema → Solución',
  story_lesson: 'Historia → Lección', before_after: 'Antes / Después',
  step_by_step: 'Paso a paso', myth_busting: 'Desmontando mitos',
  short_punchy: 'Corto e impactante', long_form_essay: 'Ensayo largo',
  data_driven: 'Basado en datos', other: 'Otro',
};

interface ArchetypeRaw {
  hook_type: string;
  post_structure: string;
  avg_ratio: number;
  example_hook: string | null;
  example_text: string | null;
}

async function getArchetypePool(): Promise<ArchetypeRaw[]> {
  const { rows } = await pool.query(`
    SELECT
      p.hook_type,
      p.post_structure,
      AVG(p.outlier_ratio)::float AS avg_ratio,
      (ARRAY_AGG(p.hook_text ORDER BY p.outlier_ratio DESC))[1] AS example_hook,
      (ARRAY_AGG(p.content_text ORDER BY p.outlier_ratio DESC))[1] AS example_text
    FROM posts p
    WHERE p.is_outlier = TRUE
      AND p.linkedin_post_id <> 'DEMO_LIVE_POST'
      AND p.hook_type IS NOT NULL AND p.hook_type != 'other'
      AND p.post_structure IS NOT NULL AND p.post_structure != 'other'
    GROUP BY p.hook_type, p.post_structure
    HAVING COUNT(*) >= 2
    ORDER BY avg_ratio DESC
    LIMIT 18
  `);
  return rows;
}

// Ask Claude to pick 3 archetypes from the pool that best fit THIS raw idea.
// Accepts a list of archetype_keys already tried so reloads return different picks.
async function selectArchetypesForIdea(
  rawIdea: string,
  archetypePool: ArchetypeRaw[],
  exclude: string[]
): Promise<ArchetypeRaw[]> {
  const excludeSet = new Set(exclude);
  const candidates = archetypePool.filter(
    (a) => !excludeSet.has(`${a.hook_type}__${a.post_structure}`)
  );
  if (candidates.length === 0) return archetypePool.slice(0, 3); // pool exhausted → reset

  const list = candidates
    .map((a, i) => {
      const hook = HOOK_LABELS[a.hook_type] || a.hook_type;
      const struct = STRUCT_LABELS[a.post_structure] || a.post_structure;
      return `${i + 1}. ${hook} + ${struct} (${a.avg_ratio.toFixed(1)}x avg ratio)`;
    })
    .join('\n');

  const response = await client.messages.create({
    model: 'claude-sonnet-4-6',
    max_tokens: 400,
    messages: [{
      role: 'user',
      content: `You're picking viral LinkedIn archetypes for a specific raw idea.

RAW IDEA:
"""
${rawIdea}
"""

AVAILABLE ARCHETYPES (hook + structure pairings, sorted by past virality):
${list}

Pick exactly 3 archetypes from the list that fit THIS specific idea best — based on the topic, tone, and what would naturally surface its punchline.

CRITICAL:
- The 3 must be MEANINGFULLY DIFFERENT from each other (different angles, not three flavors of the same shape).
- Favor archetypes that match the *content* of the idea, not just the highest ratio. A data-shock idea wants a data-shock hook; a personal anecdote wants a confession or story opener.
- Return ONLY a JSON array of 3 numbers (1-indexed positions from the list). Example: [3, 7, 12]
- No markdown, no explanation, just the JSON array.`,
    }],
  });

  const raw = response.content[0].type === 'text' ? response.content[0].text.trim() : '';
  const cleaned = raw.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
  const startIdx = cleaned.indexOf('[');
  const endIdx = cleaned.lastIndexOf(']');
  if (startIdx === -1 || endIdx === -1) return candidates.slice(0, 3);

  let picks: number[];
  try {
    picks = JSON.parse(cleaned.slice(startIdx, endIdx + 1));
    if (!Array.isArray(picks)) throw new Error('not array');
  } catch {
    return candidates.slice(0, 3);
  }

  const selected: ArchetypeRaw[] = [];
  const seen = new Set<number>();
  for (const p of picks) {
    const idx = Number(p) - 1;
    if (Number.isInteger(idx) && idx >= 0 && idx < candidates.length && !seen.has(idx)) {
      selected.push(candidates[idx]);
      seen.add(idx);
    }
    if (selected.length >= 3) break;
  }
  // Pad with remaining candidates if Claude returned fewer than 3
  for (const c of candidates) {
    if (selected.length >= 3) break;
    const key = `${c.hook_type}__${c.post_structure}`;
    if (!selected.some((s) => `${s.hook_type}__${s.post_structure}` === key)) selected.push(c);
  }
  return selected.slice(0, 3);
}

async function getOutlierContext(): Promise<string> {
  const { rows: outliers } = await pool.query(`
    SELECT p.content_text, p.hook_text, p.hook_type, p.post_structure, p.text_tone,
           p.outlier_ratio, p.likes_count, p.comments_count, p.reposts_count
    FROM posts p
    WHERE p.is_outlier = TRUE AND p.linkedin_post_id <> 'DEMO_LIVE_POST'
      AND p.content_text IS NOT NULL AND LENGTH(p.content_text) > 50
    ORDER BY p.outlier_ratio DESC
    LIMIT 8
  `);

  if (outliers.length === 0) return '';

  const lines: string[] = ['=== TOP OUTLIER POSTS (real viral examples for style reference) ==='];
  for (const p of outliers) {
    lines.push(`\n[${p.outlier_ratio}x ratio | Hook: ${p.hook_type} | Structure: ${p.post_structure} | Tone: ${p.text_tone}]`);
    lines.push(`"${(p.content_text || '').substring(0, 500)}${(p.content_text || '').length > 500 ? '…' : ''}"`);
  }
  return lines.join('\n');
}

async function generateVariant(
  rawContent: string,
  sourceType: string,
  archetype: ArchetypeRaw,
  outlierContext: string
): Promise<string> {
  const hookLabel = HOOK_LABELS[archetype.hook_type] || archetype.hook_type;
  const structLabel = STRUCT_LABELS[archetype.post_structure] || archetype.post_structure;

  const exampleSection = archetype.example_text
    ? `\nEXAMPLE of this archetype performing well (${archetype.avg_ratio.toFixed(1)}x avg ratio):\nHook: "${archetype.example_hook || ''}"\n---\n${archetype.example_text.substring(0, 500)}\n---`
    : '';

  const today = new Date();
  const todayStr = today.toISOString().slice(0, 10);
  const currentYear = today.getUTCFullYear();

  const system = `You are a LinkedIn post writer. Write a complete LinkedIn post based on a raw idea, using a SPECIFIC viral archetype.

TODAY'S DATE: ${todayStr}. The current year is ${currentYear}. If you need to reference the year, use ${currentYear} — never write "${currentYear - 1}" or an earlier year as if it were the present.

ARCHETYPE TO USE:
- Hook type: ${hookLabel} (${archetype.hook_type})
- Post structure: ${structLabel} (${archetype.post_structure})
- This archetype achieves ${archetype.avg_ratio.toFixed(1)}x average engagement in real data
${exampleSection}

${BRAND_RULES}

${POSITIONING_PRINCIPLES}

${REMIX_PRINCIPLES}

${NEETY_MECHANICS}

${CREATOR_LEARNINGS}

RULES:
- Write in the same language as the raw idea
- Keep the EXACT core idea, examples, numbers, and quotes — do NOT change the substance
- Apply the hook type strictly: the first line must follow the "${hookLabel}" pattern
- HOOK MUST ANCHOR TO OUR SECTOR (B2B sales + AI). The hook MUST reference at least one of: AI / IA / agente / agent / LLM / SDR / outbound / outreach / cold email / prospecting / pipeline / ventas / sales / B2B / SaaS / CRM / GTM / lead gen / closing / discovery / demo, OR a specific tool we live in (Claude, GPT, Clay, Apollo, HubSpot, Salesforce, n8n, Make, Zapier, etc.). A generic personal-development hook ("Hace 5 años pensaba que…", "El otro día me di cuenta…") FAILS — anyone in any industry could publish it, which dissolves our positioning. The sector anchor lives in the FIRST line, not buried in paragraph 3.
- HOOK MUST BE A SINGLE LINE (no \\n inside). Whatever counts as the hook must fit on the first physical line of the post — between 20 and 140 characters total, single line, no soft or hard line breaks before the open loop punctuation (":" "..." "👇"). LinkedIn cuts at ~210 chars before "see more"; a hook split across 2-3 lines with line breaks gets visually truncated mid-thought and the open loop never lands. The first paragraph break ONLY appears AFTER the hook is complete.
- HOOK MUST USE PUNCHY / EXTREME LANGUAGE. Whenever the meaning isn't lost, replace neutral words with vivid, physical, or hyperbolic alternatives. Stronger verbs over neutral ones (tiré > di, destrocé > superé, reventé > vendí mucho, quemé > gasté). Hyperbolic concrete adjectives over flat ones ("rampa de la muerte" > "rampa gigante", "el error más caro de mi carrera" > "un error grande", "el 80% se está extinguiendo" > "muchos fallan"). The hook should feel cinematic, not corporate. NEVER use hedge words in the hook: "quizás", "tal vez", "creo que", "puede que", "un poco", "algo", "bastante", "casi", "más o menos", "I think", "maybe", "kind of", "sort of" — they all soften the punch and signal weak conviction.
- Apply the post structure strictly: the post must follow the "${structLabel}" framework
- Short paragraphs (max 2-3 lines), blank line between them
- LIST FORMATTING: when you write a sequence of numbered items (1. 2. 3.), bullets (- • ✅ ❌) or arrows (→ ↳ ▶ 👉 👇), put each item on its own line and KEEP THEM AS A SINGLE TIGHT BLOCK — no blank line between items. The blank line goes BEFORE and AFTER the whole list, never inside it. Outliers consistently use this dense list format; spacing every list item like a paragraph reads as low-effort and breaks the rhythm.
- Personal, concrete, conversational — not corporate
- 150-400 words
- End with EXACTLY ONE CTA — pick a single closer: an opinion-forcing question, OR a "Comenta 'X' y te lo mando" lead-magnet ask (only if there's a real deliverable), OR no CTA at all (a strong claim can close). NEVER stack two CTAs at the end (no question + lead-magnet together, no two questions). One closer, sharp.
- ONE PILLAR ONLY: every post must commit to a single dominant psychological pillar (curiosity / fear / desire) and push it to the maximum. Trace amounts of the others are fine — actively triggering all three dilutes the message. Pick the one that fits the raw idea best and lean hard.
- NEVER use: "I'm excited to share", "In today's world", "Game changer", "Leverage", "Synergy"
- NEVER use markdown formatting inside the post: no **bold**, no *italic*, no \`code\`, no # headers. LinkedIn renders none of this — **word** shows up literally in the feed. Express emphasis with line breaks, caps on 1–2 words max, or punctuation instead.
- 2-3 relevant hashtags at the end

${outlierContext ? `\nVIRAL REFERENCE POSTS:\n${outlierContext}` : ''}

Respond with ONLY the post text — no preamble, no explanation.`;

  const response = await client.messages.create({
    model: 'claude-opus-4-7',
    max_tokens: 1024,
    messages: [{
      role: 'user',
      content: `Raw idea: "${rawContent}"\nSource: ${sourceType}\n\nWrite the post using the ${hookLabel} hook and ${structLabel} structure:`,
    }],
    system,
  });

  return response.content[0].type === 'text' ? response.content[0].text.trim() : '';
}

// ─── CRUD ─────────────────────────────────────────────────────────────────────

// GET /api/ideas
router.get('/', async (_req: Request, res: Response) => {
  try {
    const ideas = await PostIdeaModel.findAll();
    res.json(ideas);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// POST /api/ideas
router.post('/', async (req: Request, res: Response) => {
  try {
    const { raw_content, source_type, tags } = req.body;
    if (!raw_content?.trim()) return res.status(400).json({ error: 'raw_content is required' });

    const idea = await PostIdeaModel.create({ raw_content: raw_content.trim(), source_type, tags });
    res.status(201).json(idea);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// PATCH /api/ideas/:id
router.patch('/:id', async (req: Request, res: Response) => {
  try {
    const idea = await PostIdeaModel.update(paramId(req), req.body);
    if (!idea) return res.status(404).json({ error: 'Idea not found' });
    res.json(idea);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// DELETE /api/ideas/:id
router.delete('/:id', async (req: Request, res: Response) => {
  try {
    await PostIdeaModel.delete(paramId(req));
    res.json({ message: 'Deleted' });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// ─── Generate post from idea ───────────────────────────────────────────────────

// POST /api/ideas/:id/generate
// Generates 3 post variants, one per top viral archetype from real outlier data.
// Returns { variants: ArchetypeVariant[] }. User selects one, then auto-improve runs.
router.post('/:id/generate', async (req: Request, res: Response) => {
  const id = paramId(req);
  try {
    const idea = await PostIdeaModel.findById(id);
    if (!idea) return res.status(404).json({ error: 'Idea not found' });

    await PostIdeaModel.update(id, { status: 'generating' });

    // Optional list of archetype_keys already tried — for the "reload archetypes" UX
    const exclude: string[] = Array.isArray(req.body?.exclude) ? req.body.exclude : [];

    // Pull a wide pool of high-performing archetypes
    const archetypePool = await getArchetypePool();

    // Fallback if not enough outlier data
    if (archetypePool.length === 0) {
      archetypePool.push(
        { hook_type: 'personal_confession', post_structure: 'confession_insight_takeaway', avg_ratio: 3, example_hook: null, example_text: null },
        { hook_type: 'data_shock', post_structure: 'problem_agitate_solve', avg_ratio: 3, example_hook: null, example_text: null },
        { hook_type: 'contrarian_take', post_structure: 'contrarian_proof_reframe', avg_ratio: 3, example_hook: null, example_text: null },
      );
    }

    // Let Claude pick the 3 archetypes that fit THIS idea best, skipping ones already shown
    let archetypes: ArchetypeRaw[];
    try {
      archetypes = await selectArchetypesForIdea(idea.raw_content, archetypePool, exclude);
    } catch (selErr: any) {
      console.error('[Ideas generate] Selector failed, falling back to top-3:', selErr.message);
      archetypes = archetypePool.slice(0, 3);
    }

    if (archetypes.length === 0) {
      archetypes = archetypePool.slice(0, 3);
    }

    const outlierContext = await getOutlierContext();

    // Generate all 3 variants in parallel
    const results = await Promise.allSettled(
      archetypes.slice(0, 3).map((arch) => generateVariant(idea.raw_content, idea.source_type, arch, outlierContext))
    );

    const sanitizeText = (t: string) =>
      ensureSingleLineHook(
        t
          .replace(/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/g, '')
          // LinkedIn doesn't render markdown — strip **bold** / *italic* / `code`
          // wrappers so they don't appear as literal asterisks in the feed. We
          // tell the model not to use them in the prompt too, but defend at the
          // boundary.
          .replace(/\*\*([^*\n]+?)\*\*/g, '$1')
          .replace(/(^|[\s(])\*([^*\n]+?)\*(?=[\s).,!?]|$)/g, '$1$2')
          .replace(/`([^`\n]+?)`/g, '$1')
          .trim()
      );

    const variants = archetypes.slice(0, 3).map((arch, i) => ({
      archetype_key: `${arch.hook_type}__${arch.post_structure}`,
      archetype_label: `${HOOK_LABELS[arch.hook_type] || arch.hook_type}`,
      archetype_desc: `${STRUCT_LABELS[arch.post_structure] || arch.post_structure} · ${arch.avg_ratio.toFixed(1)}x ratio en outliers`,
      hook_type: arch.hook_type,
      post_structure: arch.post_structure,
      avg_ratio: arch.avg_ratio,
      text: results[i].status === 'fulfilled' ? sanitizeText((results[i] as PromiseFulfilledResult<string>).value) : '',
    })).filter((v) => v.text.length > 0);

    if (variants.length === 0) {
      await PostIdeaModel.update(id, { status: 'draft' });
      return res.status(500).json({ error: 'AI returned empty responses for all variants' });
    }

    // Save variants using explicit ::jsonb cast to avoid pg serialization issues
    const variantsJson = JSON.stringify(variants);
    try {
      await pool.query(
        `UPDATE post_ideas SET generated_variants = $1::jsonb, status = 'ready', updated_at = NOW() WHERE id = $2`,
        [variantsJson, id]
      );
    } catch (dbErr: any) {
      console.error('[Ideas generate] DB save failed:', dbErr.message);
      console.error('[Ideas generate] JSON payload (first 1000 chars):', variantsJson.substring(0, 1000));
      throw dbErr;
    }

    res.json({ variants });
  } catch (err: any) {
    console.error('[Ideas generate] Error:', err.message, err.stack);
    await PostIdeaModel.update(id, { status: 'draft' }).catch(() => {});
    res.status(500).json({ error: err.message });
  }
});

// POST /api/ideas/:id/save-post — save the final improved post + score
router.post('/:id/save-post', async (req: Request, res: Response) => {
  try {
    const { generated_post, generation_score } = req.body;
    const idea = await PostIdeaModel.update(paramId(req), {
      generated_post,
      generation_score: typeof generation_score === 'number' ? generation_score : null,
      status: 'ready',
    });
    res.json(idea);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// ─── Inspiration: browse & steal outlier posts ──────────────────────────────

// GET /api/ideas/inspiration — Return all outlier posts with creator info
router.get('/inspiration', async (_req: Request, res: Response) => {
  try {
    const { rows } = await pool.query(`
      SELECT p.id, p.content_text, p.hook_text, p.hook_type, p.post_structure,
             p.text_tone, p.content_type, p.outlier_ratio, p.engagement_score,
             p.likes_count, p.comments_count, p.reposts_count,
             p.published_at, p.post_url, p.topic,
             c.name AS creator_name, c.headline AS creator_headline,
             c.profile_image_url AS creator_image, c.followers_count AS creator_followers
      FROM posts p
      JOIN creators c ON c.id = p.creator_id
      WHERE p.is_outlier = TRUE
        AND p.linkedin_post_id <> 'DEMO_LIVE_POST'
        AND p.content_text IS NOT NULL
        AND LENGTH(p.content_text) > 80
      ORDER BY p.outlier_ratio DESC
    `);

    res.json({ outliers: rows, total: rows.length });
  } catch (err: any) {
    console.error('[Inspiration] Error:', err.message);
    res.status(500).json({ error: err.message });
  }
});

// POST /api/ideas/inspiration/classify — AI-classify outlier posts by topic (one-time)
router.post('/inspiration/classify', async (_req: Request, res: Response) => {
  try {
    const { rows: unclassified } = await pool.query(`
      SELECT p.id, p.content_text, p.hook_text
      FROM posts p
      WHERE p.is_outlier = TRUE
        AND p.linkedin_post_id <> 'DEMO_LIVE_POST'
        AND p.content_text IS NOT NULL
        AND LENGTH(p.content_text) > 80
        AND (p.topic IS NULL OR p.topic = '')
      ORDER BY p.outlier_ratio DESC
    `);

    if (unclassified.length === 0) {
      return res.json({ classified: 0, message: 'All outliers already classified' });
    }

    const cleanText = (t: string) =>
      (t || '')
        // Strip control chars
        .replace(/[\x00-\x1F\x7F]/g, ' ')
        // Strip lone UTF-16 surrogates (orphan halves of an emoji pair) — these
        // produce invalid JSON when the body is serialised and Anthropic's API
        // returns 400 "no low surrogate in string". Real emoji pairs are
        // preserved because the high+low pair matches as a unit elsewhere.
        .replace(/[\uD800-\uDBFF](?![\uDC00-\uDFFF])/g, '')
        // eslint-disable-next-line no-misleading-character-class
        .replace(/(^|[^\uD800-\uDBFF])[\uDC00-\uDFFF]/g, '$1')
        .replace(/"/g, "'")
        .replace(/\s+/g, ' ')
        .trim()
        .substring(0, 250);

    const BATCH_SIZE = 30;
    let totalClassified = 0;

    for (let start = 0; start < unclassified.length; start += BATCH_SIZE) {
      const batch = unclassified.slice(start, start + BATCH_SIZE);

      const postsList = batch.map((p: any, i: number) =>
        `${i + 1}. [ID:${p.id}] ${cleanText(p.content_text)}`
      ).join('\n\n');

      const response = await client.messages.create({
        model: 'claude-sonnet-4-6',
        max_tokens: 2048,
        messages: [{
          role: 'user',
          content: `Classify each LinkedIn post below into a short topic label (2-4 words max).

Use CONSISTENT labels across posts — group similar themes under the SAME label.
Good labels: "Sales Tactics", "Cold Outreach", "Hiring & Culture", "Founder Lessons", "AI & Automation", "Personal Growth", "Productivity", "Leadership", "Storytelling", "Marketing Strategy"

Posts:
${postsList}

Return a JSON object mapping post number to topic label. Example:
{"1": "Sales Tactics", "2": "Founder Lessons", "3": "Cold Outreach"}

Return ONLY the JSON object. No markdown, no explanation.`,
        }],
      });

      const rawText = response.content[0].type === 'text' ? response.content[0].text.trim() : '';
      if (!rawText) continue;

      const cleaned = rawText.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '').trim();
      const startIdx = cleaned.indexOf('{');
      const endIdx = cleaned.lastIndexOf('}');
      if (startIdx === -1 || endIdx === -1) continue;

      let mapping: Record<string, string>;
      try {
        mapping = JSON.parse(cleaned.slice(startIdx, endIdx + 1));
      } catch {
        console.error('[Classify] JSON parse error for batch starting at', start);
        continue;
      }

      for (const [numStr, topic] of Object.entries(mapping)) {
        const idx = parseInt(numStr, 10) - 1;
        if (idx < 0 || idx >= batch.length || !topic) continue;
        const postId = batch[idx].id;
        await pool.query('UPDATE posts SET topic = $1 WHERE id = $2', [topic.trim(), postId]);
        totalClassified++;
      }
    }

    res.json({ classified: totalClassified, total: unclassified.length });
  } catch (err: any) {
    console.error('[Classify] Error:', err.message);
    res.status(500).json({ error: err.message });
  }
});

// ─── Inspiration: generate ideas (brainstorming) ────────────────────────────

interface GeneratedIdea {
  title: string;
  body: string;
  sub_angle?: string;
  suggested_hook?: string;
}

const sanitizeTextShort = (t: string) =>
  (t || '').replace(/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/g, '').trim();

function parseIdeasJson(raw: string): GeneratedIdea[] {
  const cleaned = raw.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '').trim();
  const startIdx = cleaned.indexOf('[');
  const endIdx = cleaned.lastIndexOf(']');
  if (startIdx === -1 || endIdx === -1) return [];
  try {
    const parsed = JSON.parse(cleaned.slice(startIdx, endIdx + 1));
    if (!Array.isArray(parsed)) return [];
    return parsed
      .filter((x) => x && typeof x === 'object' && x.title && x.body)
      .map((x) => ({
        title: sanitizeTextShort(String(x.title)).substring(0, 180),
        body: sanitizeTextShort(String(x.body)).substring(0, 1200),
        sub_angle: x.sub_angle ? sanitizeTextShort(String(x.sub_angle)).substring(0, 60) : undefined,
        suggested_hook: x.suggested_hook ? sanitizeTextShort(String(x.suggested_hook)).substring(0, 220) : undefined,
      }))
      .filter((x) => x.title.length > 0 && x.body.length > 0);
  } catch {
    return [];
  }
}

// ─── Brainstorm v2: parametric by post type ─────────────────────────────────

type PostType =
  | 'lead_magnet' | 'opinion' | 'story' | 'listicle' | 'how_to'
  | 'contrarian' | 'data_driven' | 'behind_scenes' | 'question' | 'news_reaction';

const POST_TYPES: PostType[] = [
  'lead_magnet', 'opinion', 'story', 'listicle', 'how_to',
  'contrarian', 'data_driven', 'behind_scenes', 'question', 'news_reaction',
];

// One specialised system prompt per post type. Each one defines:
// - the canonical pattern of that post type (so the model writes the right shape)
// - examples of valid sub_angles (so 10-20 ideas come back genuinely different)
// - what the hook should look like
// The shared boilerplate (JSON shape, language matching, count, etc.) is appended
// in `buildBrainstormSystem` below.
const POST_TYPE_PROMPTS: Record<PostType, { label: string; instructions: string; subAngles: string[] }> = {
  lead_magnet: {
    label: 'Lead magnet',
    instructions: `Posts tipo "comenta SÍ y te lo mando" / "escribe GUÍA abajo y te paso el PDF". El gancho promete un recurso valioso (template, checklist, base de datos, framework, dossier, audit) a cambio de un comentario simple. La estructura típica: hook con la promesa concreta del recurso → 2-3 líneas validando por qué ese recurso es valioso (resultado, datos, ahorro de tiempo) → CTA del tipo "Comenta 'X' y te lo mando" o "Escribe Y abajo y te paso Z".

EL "suggested_hook" DEBE seguir literalmente uno de estos patrones (en el idioma del topic): "Comenta 'PALABRA' y te paso…", "Escribe SÍ debajo y te mando…", "Pon 'X' en comentarios y te envío…". El recurso prometido tiene que ser concreto y específico — no "te paso info", sino "te paso la plantilla de 12 emails outbound que usan los 30 mejores SDRs B2B".`,
    subAngles: ['plantilla', 'checklist', 'base de datos', 'framework', 'audit', 'caso real / case study'],
  },
  opinion: {
    label: 'Opinión / hot take',
    instructions: `Postura clara, primera persona, polémica pero defendible. Hook = la opinión cruda, sin matices. El cuerpo aporta 2-3 razones concretas o una anécdota corta que la sostiene. Termina con un cierre o pregunta provocadora ("Cambio mi opinión?", "¿Tengo razón o estoy loco?").

El "suggested_hook" debe sonar a opinión personal sin filler, NO a observación neutral. Ejemplos del tono: "Vendéis B2B y aún no hostáis vuestro CRM en HubSpot. Es un error caro.", "El mejor SDR que he contratado nunca había hecho ventas".`,
    subAngles: ['anti-consenso', 'anti-tendencia', 'predicción polémica', 'crítica al sector', 'autocrítica'],
  },
  story: {
    label: 'Personal story',
    instructions: `Anécdota concreta → giro → lección. Hook teaser ("Hace 6 meses perdí mi mayor cliente. Lo que aprendí cambió mi forma de vender."), cuerpo narrativo en 3-5 párrafos cortos, cierre con la lección extraída. La historia debe sentirse vivida — fecha, nombre del cliente (anonimizado o real), cifras concretas, emoción.

El "suggested_hook" es el primer párrafo (1-2 líneas) que abre el loop sin spoilear el desenlace.`,
    subAngles: ['fracaso', 'aprendizaje caro', 'momento decisivo', 'mentor / lección de otro', 'cliente difícil', 'pivote'],
  },
  listicle: {
    label: 'Listicle',
    instructions: `Hook con número específico ("5 errores", "7 tácticas", "3 patrones"), cuerpo con la lista enumerada (cada item con 1-2 líneas), cierre con CTA o reflexión. El número debe ser justificable — si pones 7 es porque tienes 7 sólidos, no para inflar.

El "suggested_hook" debe contener el número y el beneficio claro: "5 errores que vi en 30 calls de ventas B2B esta semana".`,
    subAngles: ['errores comunes', 'tácticas / playbook', 'patrones observados', 'señales de alerta', 'preguntas de entrevista', 'reglas / heurísticas'],
  },
  how_to: {
    label: 'How-to / framework',
    instructions: `Framework reproducible paso a paso. Hook con el resultado prometido ("Cómo cerré 3 deals B2B con un solo email"), cuerpo con los pasos numerados (cada uno accionable, con detalle suficiente para replicar), cierre con la promesa cumplida o el siguiente paso.

El "suggested_hook" debe empezar con "Cómo…" o "Así…" y prometer un resultado concreto.`,
    subAngles: ['proceso completo', 'mini-framework (3 pasos)', 'tactic + tool stack', 'transformación antes/después', 'anti-framework (qué NO hacer)'],
  },
  contrarian: {
    label: 'Contrarian',
    instructions: `Rompe una creencia común del sector. Hook = la creencia + tu rechazo ("Todo el mundo dice X. Es mentira."), cuerpo con la prueba concreta de por qué la creencia falla (datos, anécdota, lógica), cierre con la versión correcta o el reframe.

El "suggested_hook" debe nombrar explícitamente la creencia que estás rompiendo. Patrones: "Todo el mundo dice X. Es mentira.", "El consejo de 'X' está roto.", "X no funciona — y los datos lo demuestran."`,
    subAngles: ['mito desmontado', 'consejo común roto', 'best practice obsoleta', 'sentido común invertido', 'gurú equivocado'],
  },
  data_driven: {
    label: 'Data-driven',
    instructions: `Caso o dato específico que sorprende. Hook con la cifra impactante ("Analicé 200 emails outbound. Solo el 3% tenían lo que importa."), cuerpo desglosando la metodología y el insight, cierre con la implicación para el lector.

El "suggested_hook" debe contener una cifra concreta y un sujeto preciso. Evita números redondos vagos ("muchas empresas") — usa datos auditables ("12 de 47 deals", "3.4x ratio").`,
    subAngles: ['benchmark del sector', 'mini-estudio propio', 'análisis de competencia', 'patrón estadístico', 'caso con números'],
  },
  behind_scenes: {
    label: 'Behind-the-scenes',
    instructions: `Vulnerabilidad selectiva — muestra el "cómo se hace la salchicha" que normalmente no se cuenta. Hook con la confesión o la apertura de loop ("Lo que no te cuentan sobre cerrar tu primer deal de 6 cifras…"), cuerpo con detalles concretos del proceso real (no la versión LinkedIn), cierre con la lección o el "lo que cambiaría".

El "suggested_hook" debe sentirse íntimo y específico, nunca genérico ("mi proceso es…").`,
    subAngles: ['lo que no te cuentan', 'el coste real', 'fracaso en directo', 'proceso completo paso a paso', 'la verdad sobre…'],
  },
  question: {
    label: 'Pregunta / debate',
    instructions: `Post corto (1-3 líneas) cuya función es generar comentarios. La pregunta debe forzar una postura — no admitir respuestas tibias. Buenas preguntas tienen un sesgo claro o ponen al lector en un dilema concreto.

El "suggested_hook" ES el post entero — 1-2 frases. El "body" en el JSON sugiere por qué la pregunta funciona y cómo enmarcar las respuestas.`,
    subAngles: ['dilema binario', 'unpopular opinion (pregunta)', 'asunción cuestionada', 'escenario hipotético', 'encuesta abierta'],
  },
  news_reaction: {
    label: 'Reacción a noticia',
    instructions: `El usuario te pega una noticia del sector. Tú generas reacciones distintas — al menos un ángulo optimista, uno crítico, uno práctico ("qué hacer ahora").

El "suggested_hook" debe referenciar la noticia y aportar tu postura en la primera línea, no resumirla. El cuerpo aporta valor propio (datos, anécdota, predicción) — nunca resume la noticia ni dice "como leí en…".`,
    subAngles: ['optimista / oportunidad', 'crítico / escéptico', 'práctico / qué hacer ahora', 'predicción de segundo orden', 'caso de uso concreto'],
  },
};

function buildBrainstormSystem(postType: PostType, count: number, hasUserAngle: boolean): string {
  const meta = POST_TYPE_PROMPTS[postType];
  const angleSection = hasUserAngle
    ? `\n═══ EL ÁNGULO DEL USUARIO MANDA SOBRE TODO ═══
El usuario te ha dado un ÁNGULO / MENSAJE concreto (verás "ÁNGULO DEL USUARIO" en el mensaje). Esto es la tesis que él quiere defender. Tu trabajo NO es proponer ideas genéricas sobre el topic — es proponer ${count} formas DISTINTAS de comunicar EL ÁNGULO QUE ÉL TE DA.

Reglas duras cuando hay ángulo del usuario:
- CADA IDEA debe defender o explorar EL MISMO ÁNGULO desde un sub-ángulo distinto. No cambies de tesis.
- Si el ángulo es "el cold outreach está muerto por la IA", NO propongas ideas defendiendo lo contrario, ni ideas neutras tipo "5 tips de cold outreach".
- Lo que varía entre las ${count} ideas es el ENFOQUE / PRUEBA / FORMATO con el que comunicas la tesis, no la tesis en sí.
- El "suggested_hook" debe sonar a algo que el usuario diría — directo, con su tesis explícita o teaseada en la primera línea.
═════════════════════════════════════════════
`
    : '';

  return `Eres un estratega de contenido para LinkedIn especializado en posts tipo "${meta.label}".

═══ PATRÓN DE ESTE TIPO DE POST ═══
${meta.instructions}

═══ SUB-ÁNGULOS DISPONIBLES ═══
Cuando generes ${count} ideas, asegúrate de variar el "sub_angle" — cada idea debe atacar el tema desde un sub-ángulo distinto. Ejemplos válidos para este tipo: ${meta.subAngles.map((s) => `"${s}"`).join(', ')}. Puedes proponer otros que encajen.
${angleSection}
═══ REGLAS GENERALES ═══
- Genera EXACTAMENTE ${count} ideas, todas claramente DIFERENTES entre sí (no 3 versiones del mismo ángulo).
- Cada idea debe ser específica y accionable — no vaguedades tipo "habla sobre la importancia de X".
- Escribe en el idioma del topic / contexto que recibas. Si el topic está en español, responde en español. NO mezcles idiomas.
- Cada idea es un objeto JSON con campos: "title" (1 línea, <90 chars, resume el ángulo), "body" (2-4 líneas explicando qué se desarrollaría en el post), "sub_angle" (etiqueta corta que clasifique el ángulo dentro del tipo, en minúsculas, ej: "${meta.subAngles[0]}"), "suggested_hook" (la primera línea propuesta del post real, lista para copiar).

Responde SOLO un JSON array: [{"title","body","sub_angle","suggested_hook"}]. Sin markdown, sin texto extra, sin preámbulo.`;
}

function buildBrainstormUser(
  postType: PostType,
  topic: string,
  angle: string | undefined,
  audience: string | undefined,
  outlierContext: string | undefined,
  newsContext: string | undefined,
  count: number
): string {
  const lines: string[] = [];
  lines.push(`TOPIC: "${topic}"`);

  // The user's angle / message is the highest-signal input. Render it as a
  // visually-distinct block so the model can't miss it.
  if (angle?.trim()) {
    lines.push(
      '',
      '═══ ÁNGULO DEL USUARIO (esta es la tesis que él quiere defender — NO la cambies) ═══',
      angle.trim().substring(0, 1500),
      '═══════════════════════════════════════════════════════════════════════════════════'
    );
  }

  if (audience?.trim()) lines.push(`\nAUDIENCIA: ${audience.trim()}`);
  if (postType === 'news_reaction' && newsContext?.trim()) {
    lines.push(`\nNOTICIA / CONTEXTO:\n"""\n${newsContext.trim().substring(0, 2500)}\n"""`);
  }
  if (outlierContext) {
    lines.push(`\n${outlierContext}\n\nUsa estos posts solo como REFERENCIA del tipo de tema y tono que funciona — no copies texto, extrae los patrones y propón ángulos NUEVOS.`);
  }

  if (angle?.trim()) {
    lines.push(
      `\nGenera ${count} ideas de tipo "${POST_TYPE_PROMPTS[postType].label}" que defiendan EL ÁNGULO DEL USUARIO desde sub-ángulos distintos. NO propongas tesis alternativas — explora la suya con distintos enfoques.`
    );
  } else {
    lines.push(`\nGenera ${count} ideas de tipo "${POST_TYPE_PROMPTS[postType].label}" sobre este topic.`);
  }
  return lines.join('\n');
}

// Pull outliers as inspiration context for the brainstorm prompt.
// `grounding === 'outliers_only'` only uses validated outliers; `'all_posts'`
// widens to all posts. `'none'` returns no context (pure brainstorm).
async function getBrainstormContext(
  topic: string,
  grounding: 'outliers_only' | 'all_posts' | 'none'
): Promise<string | undefined> {
  if (grounding === 'none') return undefined;

  const params: any[] = [];
  let topicFilter = '';
  // Loose match: ILIKE %topic% on either the AI-classified topic field or
  // a substring of the content. The user's topic might be "ventas B2B" and
  // the topic column might say "Sales Tactics" — we widen the search rather
  // than miss everything.
  if (topic && topic.trim()) {
    params.push(`%${topic.trim()}%`);
    topicFilter = `AND (p.topic ILIKE $${params.length} OR p.content_text ILIKE $${params.length})`;
  }

  const outlierFilter = grounding === 'outliers_only' ? 'AND p.is_outlier = TRUE' : '';

  const { rows } = await pool.query(`
    SELECT p.content_text, p.hook_text, p.topic, p.outlier_ratio, p.likes_count, p.comments_count
    FROM posts p
    WHERE p.linkedin_post_id <> 'DEMO_LIVE_POST'
      AND p.content_text IS NOT NULL AND LENGTH(p.content_text) > 80
      ${outlierFilter}
      ${topicFilter}
    ORDER BY p.outlier_ratio DESC NULLS LAST, p.engagement_score DESC NULLS LAST
    LIMIT 12
  `, params);

  if (rows.length === 0) return undefined;

  const lines: string[] = [`POSTS DE REFERENCIA (${grounding === 'outliers_only' ? 'outliers validados' : 'todos los posts'}):`];
  rows.forEach((p: any, i: number) => {
    const text = (p.content_text || '').replace(/\s+/g, ' ').substring(0, 350);
    lines.push(`[${i + 1}] (${p.outlier_ratio ? p.outlier_ratio.toFixed(1) + 'x' : '—'}${p.topic ? ` | ${p.topic}` : ''}) "${text}${text.length === 350 ? '…' : ''}"`);
  });
  return lines.join('\n');
}

// GET /api/ideas/inspiration/trending-topics
// Returns the top topics by outlier count from the user's classified corpus.
// Used by the Generate tab as quick-pick chips ("what's hot in your data").
router.get('/inspiration/trending-topics', async (_req: Request, res: Response) => {
  try {
    const { rows } = await pool.query(`
      SELECT p.topic,
             COUNT(*)::int AS outlier_count,
             AVG(p.outlier_ratio)::float AS avg_ratio
      FROM posts p
      WHERE p.is_outlier = TRUE
        AND p.linkedin_post_id <> 'DEMO_LIVE_POST'
        AND p.topic IS NOT NULL AND p.topic != ''
      GROUP BY p.topic
      ORDER BY outlier_count DESC, avg_ratio DESC NULLS LAST
      LIMIT 12
    `);
    res.json({ topics: rows });
  } catch (err: any) {
    console.error('[Trending topics] Error:', err.message);
    res.status(500).json({ error: err.message });
  }
});

// POST /api/ideas/inspiration/brainstorm
// Unified ideation endpoint. Replaces the 4 old /generate/* routes.
router.post('/inspiration/brainstorm', async (req: Request, res: Response) => {
  try {
    const { postType, topic, angle, audience, grounding, count, newsContext } = req.body as {
      postType?: string;
      topic?: string;
      angle?: string;
      audience?: string;
      grounding?: string;
      count?: number;
      newsContext?: string;
    };

    if (!postType || !POST_TYPES.includes(postType as PostType)) {
      return res.status(400).json({ error: `postType must be one of: ${POST_TYPES.join(', ')}` });
    }
    if (!topic || !topic.trim()) {
      return res.status(400).json({ error: 'topic is required' });
    }
    const grounded = grounding === 'all_posts' || grounding === 'none' ? grounding : 'outliers_only';
    const n = Math.max(3, Math.min(20, Number(count) || 10));
    const userAngle = (angle || '').trim();

    // Pull outlier context (or skip if grounding === 'none').
    // When the user has provided an angle, the outlier search uses both the
    // topic AND the angle as keywords, so we surface posts that talk about
    // similar tesis instead of just the broad topic.
    const groundingQuery = userAngle ? `${topic.trim()} ${userAngle}`.slice(0, 200) : topic.trim();
    let outlierContext = await getBrainstormContext(groundingQuery, grounded as any);
    let groundingFallback: string | null = null;

    // If user asked for outliers-only but we found nothing, fall back to all_posts
    // rather than failing — the user gets ideas + a flag we surface in the response.
    if (!outlierContext && grounded === 'outliers_only') {
      outlierContext = await getBrainstormContext(groundingQuery, 'all_posts');
      if (outlierContext) groundingFallback = 'all_posts';
    }

    const system = buildBrainstormSystem(postType as PostType, n, !!userAngle);
    const user = buildBrainstormUser(
      postType as PostType,
      topic.trim(),
      userAngle || undefined,
      audience,
      outlierContext,
      newsContext,
      n
    );

    // Higher max_tokens for larger counts (each idea ≈ 250 tokens worst case)
    const maxTokens = Math.min(8192, 1024 + n * 320);

    const response = await client.messages.create({
      model: 'claude-sonnet-4-6',
      max_tokens: maxTokens,
      system,
      messages: [{ role: 'user', content: user }],
    });
    const raw = response.content[0].type === 'text' ? response.content[0].text.trim() : '';
    const ideas = parseIdeasJson(raw);

    if (ideas.length === 0) {
      return res.status(500).json({ error: 'No se pudieron generar ideas, intenta de nuevo' });
    }

    res.json({
      ideas,
      meta: {
        postType,
        grounding: grounded,
        groundingFallback, // null unless we silently widened from outliers_only → all_posts
        count: ideas.length,
        requested: n,
      },
    });
  } catch (err: any) {
    console.error('[Brainstorm] Error:', err.message);
    res.status(500).json({ error: err.message });
  }
});

export default router;
