import { useState, useRef, useEffect, useMemo } from 'react';
import LinkedInPostPreview from '../components/postcreator/LinkedInPostPreview';
import CreatorProfileForm from '../components/postcreator/CreatorProfileForm';
import PostChecklist, { scorePost } from '../components/postcreator/PostChecklist';
import MarkdownMessage from '../components/postcreator/MarkdownMessage';
import ImageGenerator from '../components/postcreator/ImageGenerator';

const BASE = import.meta.env.VITE_API_URL || '';

interface Message {
  role: 'user' | 'assistant';
  content: string;
}

interface CreatorProfile {
  name: string | null;
  headline: string | null;
  profile_image_url: string | null;
  followers_count: number;
}

const SUGGESTIONS = [
  'Write me a viral LinkedIn post about hiring mistakes',
  'Create a post about leadership lessons using the best-performing archetype',
  'Write 3 variations of a post about AI replacing jobs',
  'Analyze this topic and give me the best angle: remote work vs office',
];

type Tab = 'chat' | 'profile';

// Extract post blocks from an assistant message. Tries several strategies in
// order so it works whether the model emits `---` separators, numbered
// "OPCIÓN" / "OPTION" / "VARIANTE" headings, fenced code blocks, or none.
function extractPostBlocks(content: string): string[] {
  const cleaned = content.trim();
  if (cleaned.length < 50) return [];

  // 1. `---` delimited (legacy explicit separator)
  const dashed = cleaned.split(/\n---+\n/).map((b) => b.trim()).filter((b) => b.length > 50);
  if (dashed.length >= 2) return dashed;

  // 2. Numbered "OPCIÓN N" / "OPTION N" / "VARIANTE N" / "VERSIÓN N" headings.
  // This is what the chat actually emits most of the time, and is what the
  // user sees in the screenshot. Each match starts a new block; the block
  // runs until the next match or end of message.
  const optionRegex =
    /(?:^|\n)\s*(?:📌|✨|🎯|📝|⭐)?\s*(?:OPCIÓN|OPCION|OPTION|VARIANT|VARIANTE|VERSIÓN|VERSION|VARIACIÓN|VARIACION|VARIATION)\s*\d+\s*[:\-—]/gi;
  const matches = [...cleaned.matchAll(optionRegex)];
  if (matches.length >= 2) {
    const blocks: string[] = [];
    for (let i = 0; i < matches.length; i++) {
      const start = matches[i].index ?? 0;
      const end = i + 1 < matches.length ? (matches[i + 1].index ?? cleaned.length) : cleaned.length;
      blocks.push(cleaned.slice(start, end).trim());
    }
    return blocks.filter((b) => b.length > 50);
  }

  // 3. Fenced code blocks (the model sometimes wraps the post in ```)
  const fenceMatches = [...cleaned.matchAll(/```(?:[a-zA-Z0-9_-]*\n)?([\s\S]+?)```/g)];
  if (fenceMatches.length >= 1) {
    const blocks = fenceMatches.map((m) => m[1].trim()).filter((b) => b.length > 50);
    if (blocks.length >= 1) return blocks;
  }

  // 4. Fall back: treat the whole message as a single block. The user can
  // always click "send to preview" and trim by hand.
  return [cleaned];
}

// Within a single detected block, find the actual post text. The chat often
// wraps the post in commentary ("📌 OPCIÓN 1: archetype name…\n\n<post>\n\nPor
// qué funciona: …"). We strip leading heading lines and trailing meta lines
// so the preview gets the post body, not the wrapper text.
function cleanBlockForPreview(block: string): string {
  let text = block.trim();

  // Strip a leading "OPCIÓN N: …" heading line and any immediately-following
  // metadata line in parentheses (e.g. "(Arquetipo con 5.8x ratio…)").
  text = text.replace(
    /^\s*(?:📌|✨|🎯|📝|⭐)?\s*(?:OPCIÓN|OPCION|OPTION|VARIANT|VARIANTE|VERSIÓN|VERSION|VARIACIÓN|VARIACION|VARIATION)\s*\d+[^\n]*\n+/i,
    ''
  );
  text = text.replace(/^\s*\([^)]*\)\s*\n+/, '');

  // Strip a trailing "Por qué funciona:" / "Why this works:" commentary block
  // (everything from that label to the end of the block).
  text = text.replace(/\n+(?:Por qué funciona|Why this works|Why it works)[\s\S]*$/i, '');

  // Strip surrounding code-block fences if any survived.
  text = text.replace(/^```[a-zA-Z0-9_-]*\n?/, '').replace(/\n?```\s*$/, '');

  return text.trim();
}

export default function PostCreator() {
  const [tab, setTab] = useState<Tab>('chat');
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState('');
  const [streaming, setStreaming] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [profile, setProfile] = useState<CreatorProfile | null>(null);
  const [previewText, setPreviewText] = useState<string>('');
  const [manualPreview, setManualPreview] = useState<string>('');
  // The right column shows the FINAL artifact (post text + image) plus its
  // tools (score + image generator) all together, no tabs. The user wanted
  // to see post + score + image-control simultaneously, not switch contexts.
  const [editingText, setEditingText] = useState(false);
  // Image generated by the AI generator panel. When set, it's embedded into
  // the LinkedIn preview where the post image would naturally appear.
  const [generatedImageUrl, setGeneratedImageUrl] = useState<string | null>(null);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  // Load profile on mount
  useEffect(() => {
    fetch(`${BASE}/api/post-creator/profile`)
      .then((r) => r.json())
      .then((data) => {
        if (data && data.id) setProfile(data);
      })
      .catch(() => {});
  }, []);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  useEffect(() => {
    if (textareaRef.current) {
      textareaRef.current.style.height = 'auto';
      textareaRef.current.style.height = Math.min(textareaRef.current.scrollHeight, 200) + 'px';
    }
  }, [input]);

  // Auto-update preview with the latest post block from the last assistant message
  useEffect(() => {
    for (let i = messages.length - 1; i >= 0; i--) {
      if (messages[i].role === 'assistant') {
        const blocks = extractPostBlocks(messages[i].content);
        if (blocks.length > 0) {
          // Pick longest block (typically the full post) and strip wrapper text
          const longest = blocks.reduce((a, b) => (a.length > b.length ? a : b));
          setPreviewText(cleanBlockForPreview(longest));
          return;
        }
      }
    }
  }, [messages]);

  // Live score for the Score tab label. Computed here (not inside PostChecklist)
  // so the badge updates even when the user is on the Preview or Image tab.
  const liveScore = useMemo(() => {
    const text = manualPreview || previewText;
    if (!text || text.trim().length < 20) return null;
    return scorePost(text).overall;
  }, [manualPreview, previewText]);

  const sendMessage = async (text?: string) => {
    const content = text || input.trim();
    if (!content || streaming) return;

    setInput('');
    setError(null);

    const userMsg: Message = { role: 'user', content };
    const newMessages = [...messages, userMsg];
    setMessages([...newMessages, { role: 'assistant', content: '' }]);
    setStreaming(true);

    try {
      const res = await fetch(`${BASE}/api/chat`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          messages: newMessages.map((m) => ({ role: m.role, content: m.content })),
        }),
      });

      if (!res.ok) {
        const err = await res.json();
        throw new Error(err.error || `Error ${res.status}`);
      }

      const reader = res.body?.getReader();
      if (!reader) throw new Error('No reader available');

      const decoder = new TextDecoder();
      let assistantContent = '';

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        const chunk = decoder.decode(value, { stream: true });
        const lines = chunk.split('\n');

        for (const line of lines) {
          if (!line.startsWith('data: ')) continue;
          const data = line.slice(6);
          if (data === '[DONE]') continue;

          try {
            const parsed = JSON.parse(data);
            if (parsed.error) throw new Error(parsed.error);
            if (parsed.text) {
              assistantContent += parsed.text;
              setMessages((prev) => {
                const updated = [...prev];
                updated[updated.length - 1] = { role: 'assistant', content: assistantContent };
                return updated;
              });
            }
          } catch {}
        }
      }
    } catch (err: any) {
      setError(err.message);
      setMessages((prev) => prev.slice(0, -1));
    } finally {
      setStreaming(false);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      sendMessage();
    }
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
  };

  const activePreviewText = manualPreview || previewText;

  return (
    <div className="flex flex-col h-[calc(100vh-80px)]">
      {/* Compact header — title + tabs share a single 48px row.
          The long descriptive subtitle from the original layout was
          eating ~110px of vertical space and only restated what the
          page already implies, so it's been removed. The inline
          subtitle keeps a hint of context for first-time visitors. */}
      <div className="flex items-center gap-6 border-b border-border mb-3 pr-1">
        <div className="flex items-baseline gap-3 py-2 flex-shrink-0">
          <h1 className="text-lg font-semibold text-text-primary leading-none">Post Creator</h1>
          <span className="hidden md:inline text-[11px] text-text-muted leading-none">
            AI writer trained on your outlier data
          </span>
        </div>
        <div className="flex gap-1 ml-auto">
          <button
            onClick={() => setTab('chat')}
            className={`px-4 py-2 text-sm font-medium border-b-2 -mb-px transition-colors ${
              tab === 'chat'
                ? 'border-accent text-accent'
                : 'border-transparent text-text-muted hover:text-text-secondary'
            }`}
          >
            Chat
          </button>
          <button
            onClick={() => setTab('profile')}
            className={`px-4 py-2 text-sm font-medium border-b-2 -mb-px transition-colors ${
              tab === 'profile'
                ? 'border-accent text-accent'
                : 'border-transparent text-text-muted hover:text-text-secondary'
            }`}
          >
            My Profile {profile?.name ? `· ${profile.name}` : ''}
          </button>
        </div>
      </div>

      {tab === 'profile' ? (
        <div className="overflow-y-auto">
          <CreatorProfileForm onSaved={(p) => setProfile(p)} />
        </div>
      ) : (
        <div className="flex-1 flex gap-4 min-h-0">
          {/* Chat column */}
          <div className="flex-1 flex flex-col min-w-0">
            <div className="flex-1 overflow-y-auto space-y-4 pb-4">
              {messages.length === 0 && (
                <div className="flex flex-col items-center justify-center h-full text-center">
                  <div className="text-5xl mb-4">&#x270D;&#xFE0F;</div>
                  <h2 className="text-xl font-semibold text-text-primary mb-2">Create viral LinkedIn posts</h2>
                  <p className="text-text-muted text-sm max-w-md mb-4">
                    Tell me a topic, audience, or goal and I'll write posts using the patterns
                    that actually produce outliers in your data.
                  </p>
                  {!profile?.name && (
                    <button
                      onClick={() => setTab('profile')}
                      className="text-xs text-accent hover:text-accent-light mb-6"
                    >
                      → Link your LinkedIn profile for personalized posts
                    </button>
                  )}
                  <div className="flex flex-wrap gap-2 max-w-2xl justify-center">
                    {SUGGESTIONS.map((s, i) => (
                      <button
                        key={i}
                        onClick={() => sendMessage(s)}
                        className="px-3 py-2 bg-bg-card border border-border rounded-lg text-xs text-text-secondary hover:border-accent/50 hover:text-text-primary transition-colors text-left"
                      >
                        {s}
                      </button>
                    ))}
                  </div>
                </div>
              )}

              {messages.map((msg, i) => (
                <div key={i} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                  <div
                    className={`max-w-[90%] rounded-xl px-4 py-3 ${
                      msg.role === 'user'
                        ? 'bg-accent/20 text-text-primary'
                        : 'bg-bg-card border border-border text-text-primary'
                    }`}
                  >
                    {msg.role === 'assistant' ? (
                      <div>
                        <MarkdownMessage content={msg.content} />

                        {msg.content && !streaming && (() => {
                          const blocks = extractPostBlocks(msg.content);
                          const showPerBlockButtons = blocks.length > 1;
                          return (
                            <div className="flex gap-1.5 mt-3 pt-2 border-t border-border/50 flex-wrap items-center">
                              {showPerBlockButtons ? (
                                blocks.map((block, bi) => (
                                  <button
                                    key={bi}
                                    onClick={() => {
                                      const clean = cleanBlockForPreview(block);
                                      setManualPreview(clean);
                                      setPreviewTab('preview');
                                    }}
                                    className="text-[11px] px-2.5 py-1 rounded-md border border-accent/30 bg-accent/10 text-accent hover:bg-accent/20 transition-colors"
                                  >
                                    📤 Preview opción {bi + 1}
                                  </button>
                                ))
                              ) : (
                                <button
                                  onClick={() => {
                                    const block = blocks[0] || msg.content;
                                    const clean = cleanBlockForPreview(block);
                                    setManualPreview(clean);
                                    setPreviewTab('preview');
                                  }}
                                  className="text-[11px] px-2.5 py-1 rounded-md border border-accent/30 bg-accent/10 text-accent hover:bg-accent/20 transition-colors"
                                >
                                  📤 Send to preview
                                </button>
                              )}
                              <span className="ml-auto flex gap-2">
                                <button
                                  onClick={() => copyToClipboard(msg.content)}
                                  className="text-[10px] text-text-muted hover:text-accent transition-colors"
                                >
                                  Copy all
                                </button>
                              </span>
                            </div>
                          );
                        })()}

                        {streaming && i === messages.length - 1 && (
                          <span className="inline-block w-2 h-4 bg-accent animate-pulse ml-0.5" />
                        )}
                      </div>
                    ) : (
                      <p className="text-sm whitespace-pre-wrap">{msg.content}</p>
                    )}
                  </div>
                </div>
              ))}
              <div ref={messagesEndRef} />
            </div>

            {error && (
              <div className="bg-danger/10 border border-danger/30 rounded-lg p-3 mb-3 text-danger text-sm">
                {error}
              </div>
            )}

            <div className="border-t border-border pt-4">
              <div className="flex gap-3 items-end">
                <textarea
                  ref={textareaRef}
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  onKeyDown={handleKeyDown}
                  placeholder="Describe the post you want to create... (topic, audience, goal)"
                  rows={1}
                  className="flex-1 bg-bg-card border border-border rounded-xl px-4 py-3 text-sm text-text-primary placeholder:text-text-muted focus:outline-none focus:border-accent/50 resize-none"
                  disabled={streaming}
                />
                <button
                  onClick={() => sendMessage()}
                  disabled={!input.trim() || streaming}
                  className="px-5 py-3 bg-accent text-bg-primary rounded-xl text-sm font-medium disabled:opacity-40 hover:bg-accent-light transition-colors whitespace-nowrap"
                >
                  {streaming ? 'Writing...' : 'Send'}
                </button>
              </div>
            </div>
          </div>

          {/* Preview column — split into 3 tabs (Preview / Score / Image)
              instead of one tall scroll, so the user can jump between
              contexts without losing place. */}
          <div className="w-[460px] flex-shrink-0 flex flex-col min-h-0">
            {/* Header: title + tab bar. Stays at the top of the column as a
                flex sibling above the scrolling content pane. */}
            <div className="flex-shrink-0 pb-2">
              <div className="flex items-center justify-between mb-2">
                <h3 className="text-sm font-semibold text-text-primary">LinkedIn Preview</h3>
                {activePreviewText && (
                  <div className="flex items-center gap-2 text-[10px] text-text-muted">
                    <button
                      onClick={() => copyToClipboard(activePreviewText)}
                      className="hover:text-accent transition-colors"
                      title="Copiar texto"
                    >
                      📋 Copiar
                    </button>
                    <span className="text-border">·</span>
                    <button
                      onClick={() => setEditingText((v) => !v)}
                      className={`transition-colors ${editingText ? 'text-accent' : 'hover:text-accent'}`}
                      title="Editar texto a mano"
                    >
                      ✏️ Editar
                    </button>
                    <span className="text-border">·</span>
                    <button
                      onClick={() => {
                        setManualPreview('');
                        setPreviewText('');
                        setEditingText(false);
                        setGeneratedImageUrl(null);
                      }}
                      className="hover:text-danger transition-colors"
                      title="Limpiar preview"
                    >
                      ✕ Clear
                    </button>
                  </div>
                )}
              </div>

              {/* Score quick-view chip — always visible at the top while
                  there's a preview, so the user sees the score without
                  scrolling down to the full PostChecklist below. */}
              {activePreviewText && liveScore != null && (
                <div className="flex items-center gap-2 text-[11px] text-text-muted">
                  <span
                    className={`px-2 py-0.5 rounded-full font-semibold ${
                      liveScore >= 75
                        ? 'bg-green-500/15 text-green-400'
                        : liveScore >= 50
                        ? 'bg-amber-500/15 text-amber-400'
                        : 'bg-red-500/15 text-red-400'
                    }`}
                  >
                    📊 {liveScore}/100
                  </span>
                  <span className="text-text-muted">
                    {liveScore >= 75 ? 'Viral-ready' : liveScore >= 50 ? 'Decent' : 'Needs work'}
                  </span>
                </div>
              )}
            </div>

            {/* Stacked content — preview + score + image generator visible
                together so the user reviews the FINAL artifact (text + image
                + score) in a single scroll. */}
            <div className="flex-1 overflow-y-auto pb-4 space-y-4">
              {!activePreviewText ? (
                <div className="bg-bg-card border border-dashed border-border rounded-xl p-8 text-center text-text-muted text-xs">
                  Your post preview will appear here once the AI generates content.
                  <br />
                  <br />
                  You can also paste any text below to preview it.
                  <textarea
                    value={manualPreview}
                    onChange={(e) => setManualPreview(e.target.value)}
                    rows={5}
                    className="w-full mt-3 bg-bg-primary border border-border rounded-lg px-3 py-2 text-xs text-text-secondary focus:outline-none focus:border-accent/50 resize-none text-left"
                    placeholder="Paste post text..."
                  />
                </div>
              ) : (
                <>
                  {/* 1. The post itself, with the AI image embedded inside */}
                  <div>
                    <LinkedInPostPreview
                      text={activePreviewText}
                      authorName={profile?.name}
                      authorHeadline={profile?.headline}
                      authorImage={profile?.profile_image_url}
                      followersCount={profile?.followers_count}
                      externalImageUrl={generatedImageUrl}
                    />
                    {editingText && (
                      <div className="mt-3 max-w-lg mx-auto">
                        <textarea
                          value={activePreviewText}
                          onChange={(e) => setManualPreview(e.target.value)}
                          rows={8}
                          className="w-full bg-bg-card border border-accent/30 rounded-lg px-3 py-2 text-xs text-text-secondary focus:outline-none focus:border-accent/50 resize-y"
                          placeholder="Edit the post to see the preview update..."
                        />
                        <p className="text-[10px] text-text-muted mt-1">
                          Los cambios se reflejan en vivo en el preview de arriba y en el score.
                        </p>
                      </div>
                    )}
                  </div>

                  {/* 2. Image generator panel — produces the image embedded above */}
                  <div className="max-w-lg mx-auto">
                    <ImageGenerator
                      postContext={activePreviewText}
                      defaultOpen
                      onResult={(r) =>
                        setGeneratedImageUrl(`data:image/png;base64,${r.b64_json}`)
                      }
                    />
                  </div>

                  {/* 3. Full score panel with all detail (collapsible internal sections) */}
                  <div className="max-w-lg mx-auto">
                    <PostChecklist text={activePreviewText} onImproved={setManualPreview} />
                  </div>
                </>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
